import {sections,fieldsFor,typeLabels,valueFor,advancedKeys,matchesAxle,pairKey,winterTypes,normalizeWinterFilters,setSeason} from './search-model.js';
import {wheelSpinner,withLoading} from './loading.js';
import {startCheckout,renderShopPage} from './shop.js';
import {createSelection,selectionText,copyText} from './share.js';
import {money,normalize,escapeHTML as h,effectiveOffer,formatSize,filterProducts,facetOptions,cartTotals,parseFilters,serializeFilters,paginationPages} from './domain.js';
const $=(s,r=document)=>r.querySelector(s), main=$('#main'), dialog=$('#dialog');
const catalog=window.IMKONEX_DATA, products=catalog.products, byId=new Map(products.map(p=>[p.id,p]));
const portal=window.IMKONEX_CONFIG?.portal===true;
const paths={moto:'M8 17a4 4 0 1 1-8 0 4 4 0 0 1 8 0Zm16 0a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 17l5-8h7l4 8M13 5h3l4 12M6 7h5',special:'M2 15h12V9H7V4h5v5M14 13h4l4 6h-7M8 19a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm6 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',tube:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Zm-5 0a5 5 0 1 1-10 0 5 5 0 0 1 10 0Z',sensor:'M8 5h8v14H8V5Zm4-4v4M4 8a7 7 0 0 0 0 8M20 8a7 7 0 0 1 0 8',tools:'m4 20 9-9M14 3a5 5 0 0 0-3 8 5 5 0 0 0 8-3l-4 1-1-6ZM2 18l4 4',oil:'M7 6h10v16H5V8l2-2Zm1-5h8v5H8V1Zm4 10-3 5a3 3 0 1 0 6 0l-3-5',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',compare:'M5 20V10M12 20V4M19 20v-7',bag:'M5 7h14l1 14H4L5 7Zm3 0V5a4 4 0 0 1 8 0v2',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',close:'m6 6 12 12M6 18 18 6',arrow:'M4 12h16m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14',minus:'M5 12h14',check:'m5 12 4 4L19 6',car:'m3 10 2-6h14l2 6M2 10h20v9H2v-9Zm3 9v3m14-3v3M5 14h3m8 0h3',wheel:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0ZM12 2v7m0 6v7M2 12h7m6 0h7M9 12a3 3 0 1 0 6 0 3 3 0 0 0-6 0Z',snow:'M12 2v20M3 7l18 10M3 17 21 7M8 4l4 3 4-3M8 20l4-3 4 3',sun:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8ZM12 1v3m0 16v3M1 12h3m16 0h3',filter:'M4 7h16M4 17h16M8 4v6m8 4v6',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15',truck:'M1 5h13v12H1V5Zm13 4h4l4 5v3h-8M7 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0ZM21 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z'};
const icon=n=>`<svg class="icon" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.wheel}"/></svg>`;
const imageUrl=p=>window.IMKONEX_IMAGE_MAP?.[p]||(p.startsWith('https://')?p:'./'+p);
const memory=new Map(),prefix='imx:snapshot:';
function load(k,def){try{return memory.get(k)??JSON.parse(localStorage.getItem(prefix+k))??def;}catch{return memory.get(k)??def;}}
function save(k,v){memory.set(k,v);try{localStorage.setItem(prefix+k,JSON.stringify(v));}catch{}}
const validIds=items=>Array.isArray(items)?[...new Set(items.filter(id=>byId.has(id)))]:[];
let favorites=validIds(load('favorites',[])),compare=validIds(load('compare',[])).slice(0,4);
let cart=load('cart',[]);cart=Array.isArray(cart)?cart.filter(l=>byId.has(l.id)&&Number.isInteger(l.quantity)&&l.quantity>0&&l.quantity<=20):[];
let filters=parseFilters(location.hash.split('?')[1]),page=1,mode='size',activeVehicle=null,toastTimer,vehicleRequest=0;
const priceChecked=new Set();let priceLoading=false;
let pairChoice={front:null,rear:null},brandQuery='';
const vehicle={make:'',model:'',years:'',modification:'',makes:[],models:[],ranges:[],modifications:[],busy:false,error:''};
const seasons={summer:'Летние',winter:'Зимние',allseason:'Всесезонные',unknown:'Сезон уточняется'};
const categoryNames={passenger:'Легковые',truck:'Грузовые',special:'Спецтехника',moto:'Мото',other:'Другие шины',tubes:'Камеры',wheels:'Диски',sensors:'Датчики давления',consumables:'Расходники',oils:'Масла'};
const route=()=>location.hash.slice(1).split('?')[0]||'catalog';
const selected=(a,b)=>String(a)===String(b)?' selected':'';
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3400);}
function counts(){for(const [key,value] of [['favorites',favorites.length],['compare',compare.length],['cart',cart.reduce((s,l)=>s+l.quantity,0)]]){const el=$('#'+key+'-count');el.textContent=value;el.hidden=!value;}}
function heading(title){return `<div class="breadcrumb"><a href="#catalog">Главная</a><span>/</span><span>${h(title)}</span></div><div class="page-heading"><h1>${h(title)}</h1></div>`;}
function empty(title,note){return `<div class="empty-state">${icon('wheel')}<h2>${h(title)}</h2><p>${h(note)}</p><a href="#catalog" class="btn btn-primary">В каталог ${icon('arrow')}</a></div>`;}
function showDialog(title,html){delete dialog.dataset.productId;$('#dialog-content').innerHTML=`<div class="dialog-header"><h2 id="dialog-title">${h(title)}</h2><button class="icon-btn" data-action="close-dialog" aria-label="Закрыть">${icon('close')}</button></div><div class="dialog-body">${html}</div>`;dialog.showModal();}
function sync(){
 const drawer=$('#filters'),open=drawer?.classList.contains('open'),scroll=drawer?.scrollTop||0;
 const active=document.activeElement,insideDrawer=drawer?.contains(active),focusKey=active?.id?'#'+active.id:active?.dataset.brand?'[data-brand='+JSON.stringify(active.dataset.brand)+']':active?.dataset.filter?'[data-filter='+JSON.stringify(active.dataset.filter)+']':active?.dataset.action?'[data-action='+JSON.stringify(active.dataset.action)+'][data-value='+JSON.stringify(active.dataset.value||'')+']':null;
 page=1;filters=normalizeWinterFilters(filters);const hash='#'+(route()==='favorites'?'favorites':'catalog')+'?'+serializeFilters(filters);try{history.replaceState(null,'',hash);}catch{}render();
 if(open){setFiltersOpen(true,false);$('#filters').scrollTop=scroll;}
 if(focusKey){try{$(focusKey,open&&insideDrawer?$('#filters'):document)?.focus({preventScroll:true});}catch{}}
}
function setFiltersOpen(open,focus=true){
 const drawer=$('#filters');if(!drawer)return;drawer.classList.toggle('open',open);
 document.body.classList.toggle('filters-open',open);$('[data-action="open-filters"]')?.setAttribute('aria-expanded',String(open));
 if(focus)$(open?'[data-action="close-filters"]':'[data-action="open-filters"]')?.focus();
}
function winterControl(){return filters.kind==='tires'&&filters.season==='winter'?`<div class="winter-type-control"><span class="filter-label">Тип зимних шин</span><div class="winter-type-options" role="group" aria-label="Тип зимних шин">${winterTypes.map(([value,label])=>`<button type="button" class="season-btn ${filters.winterType===value?'active':''}" data-action="winter-type" data-value="${value}" aria-pressed="${filters.winterType===value}">${h(label)}</button>`).join('')}</div></div>`:'';}
function seasonalFinder(){return filters.kind==='tires'?`<div class="seasonal-finder"><label class="field"><span>Сезон</span><select data-filter="season" aria-label="Сезон шин">${[['','Любой'],['summer','Летние'],['winter','Зимние'],['allseason','Всесезонные']].map(([value,label])=>`<option value="${value}"${selected(filters.season,value)}>${label}</option>`).join('')}</select></label>${winterControl()}</div>`:'';}

function effectiveFilters(){return {...filters,...(activeVehicle?{vehicleIds:activeVehicle.ids}:{})};}
function hero(){const title=filters.category?categoryNames[filters.category]:categoryNames[filters.kind]||'Шины и диски';return `<section class="hero shop-hero"><div class="hero-copy"><span class="eyebrow">ШИНЫ И ДИСКИ</span><h1>${filters.category||filters.kind!=='tires'?h(title):'Ваш маршрут.<br><em>Ваш комплект.</em>'}</h1><p>${filters.category==='truck'?'Для грузовых автомобилей, тягачей и прицепов.':filters.category==='moto'?'Для мотоциклов и квадроциклов.':filters.category==='special'?'Для строительной, складской и сельскохозяйственной техники.':'Точный подбор. Детали, которые имеют значение.'}</p><a href="#guide" class="hero-help">Помочь с выбором ↗</a></div><div class="hero-visual" aria-hidden="true"><span class="hero-orbit"></span><img class="hero-tire" src="./assets/products/R5019.png" alt=""></div></section>`;}
const accessoryKinds=['sensors','consumables','oils'];
function categories(){return `<nav class="shop-sections" aria-label="Разделы магазина">${sections.map(([kind,cat,label,ico])=>`<button data-action="segment" data-kind="${kind}" data-category="${cat}" class="${filters.kind===kind&&filters.category===cat?'active':''}" aria-pressed="${filters.kind===kind&&filters.category===cat}">${icon(ico)}<span>${h(label)}</span></button>`).join('')}</nav>`;}
function field(key,label){const values=facetOptions(products,effectiveFilters(),key);return `<label class="field"><span>${h(label)}</span><select data-filter="${key}" name="${key}" aria-label="${h(label)}"><option value="">${values.length?'Любой':'Не указан'}</option>${values.map(v=>`<option value="${h(v)}"${selected(filters[key],v)}>${h(typeLabels[v]||v)}</option>`).join('')}</select></label>`;}
function vehicleSelect(key,label,values,disabled){return `<label class="field"><span>${h(label)}</span><select data-vehicle="${key}" aria-label="${h(label)}" ${disabled?'disabled':''}><option value="">Выберите</option>${values.map(v=>{const value=typeof v==='string'?v:v.value,label=typeof v==='string'?v:v.label;return `<option value="${h(value)}"${selected(vehicle[key],value)}>${h(label)}</option>`;}).join('')}</select></label>`;}
function vehiclePanel(){if(!portal)return `<div class="vehicle-offline"><div>${icon('car')}<h3>Подберём комплект для вашего автомобиля</h3><p>Назовите марку, модель и год выпуска — мы поможем проверить размеры.</p></div><a class="btn btn-primary" href="tel:88003013688">Связаться с менеджером ${icon('arrow')}</a></div>`;return `<div class="vehicle-fields">${vehicleSelect('make','Марка',vehicle.makes,vehicle.busy&&!vehicle.makes.length)}${vehicleSelect('model','Модель',vehicle.models,!vehicle.make||vehicle.busy)}${vehicleSelect('years','Годы выпуска',vehicle.ranges.map(r=>({value:r.begin+':'+r.end,label:r.begin===r.end?String(r.begin):r.begin+'–'+r.end})),!vehicle.model||vehicle.busy)}${vehicleSelect('modification','Модификация',vehicle.modifications,!vehicle.years||vehicle.busy)}<button class="btn btn-primary" data-action="vehicle-search" ${!vehicle.modification||vehicle.busy?'disabled':''}>${vehicle.busy?wheelSpinner('Загрузка'):'Найти комплект'} ${icon('arrow')}</button></div><p class="vehicle-hint" role="status">${h(vehicle.error||(vehicle.busy?'Загружаем варианты…':'Подбор по штатным размерам. Учитывайте комплектацию и установленные тормоза.'))}</p>`;}
function selector(){const canCar=filters.kind==='wheels'||filters.kind==='tires'&&['','passenger'].includes(filters.category);const heading=filters.category==='truck'?'Подбор грузовых шин':filters.category==='moto'?'Подбор мотошин':filters.category==='special'?'Подбор для спецтехники':filters.kind==='oils'?'Подбор масла':filters.kind==='sensors'?'Датчики давления':filters.kind==='consumables'?'Расходники и крепёж':'Подберите свой комплект';const sizeFields=fieldsFor(filters.kind,filters.category);return `<section id="selector" class="selector"><div class="selector-top"><div><span class="eyebrow">ПОДБОР БЕЗ ЛИШНИХ ШАГОВ</span><h2>${heading}</h2></div>${canCar?`<div class="selection-mode" role="group" aria-label="Способ подбора"><button data-action="mode" data-value="size" class="${mode==='size'?'active':''}">По размеру</button><button data-action="mode" data-value="car" class="${mode==='car'?'active':''}">По автомобилю</button></div>`:''}</div>${seasonalFinder()}${canCar&&mode==='car'?vehiclePanel():`<div class="selector-fields category-fields">${sizeFields.map(([k,l])=>field(k,l)).join('')}${filters.kind==='sensors'?'<p class="selection-note">Найдите по артикулу или названию. Совместимость датчика и частоту проверим перед заказом.</p>':''}</div>${filters.kind==='tires'&&['','passenger','moto'].includes(filters.category)?`<label class="staggered-switch"><input type="checkbox" data-filter="staggered" ${filters.staggered?'checked':''}><span><strong>Разноширокий комплект</strong><small>Свои размеры для передней и задней оси</small></span></label>${filters.staggered?rearFields():''}`:''}<div class="selector-bottom"><span>${filters.staggered?'Сверьте размеры обеих осей с рекомендациями производителя.':'Параметры можно менять в любом порядке.'}</span><button class="btn btn-primary" data-action="show-results">Показать варианты ${icon('arrow')}</button></div>`}</section>`;}
function sidebar(){
 const brands=[...new Set([...facetOptions(products,effectiveFilters(),'brands'),...filters.brands])].sort((a,b)=>a.localeCompare(b,'ru'));
 const checkbox=(key,label)=>`<label class="check-row"><input type="checkbox" data-filter="${key}" ${filters[key]?'checked':''}><span>${label}</span></label>`;
 return `<aside class="filters sidebar" id="filters" aria-label="Фильтры товаров"><div class="filter-heading"><h2>Детали подбора</h2><button class="text-link" data-action="reset">Сбросить</button><button class="icon-btn filter-close" data-action="close-filters" aria-label="Закрыть фильтры">${icon('close')}</button></div>
 ${filters.kind==='tires'?`<section class="filter-section"><h3>Сезон</h3><div class="season-pills" role="group" aria-label="Сезон">${[['','Все'],['summer','Лето'],['winter','Зима'],['allseason','Всесезонные']].map(([v,l])=>`<button class="season-btn ${filters.season===v?'active':''}" data-action="season" data-value="${v}" aria-pressed="${filters.season===v}">${h(l)}</button>`).join('')}</div>${winterControl()}</section>`:filters.kind==='wheels'?`<section class="filter-section"><h3>Посадка диска</h3>${field('et','Вылет ET')}${field('dia','Отверстие DIA')}</section>`:''}
 <section class="filter-section"><h3>Производитель${filters.kind==='tires'?' шин':''}</h3><input id="brand-search" class="brand-search" type="search" placeholder="Найти производителя" aria-label="Найти производителя" autocomplete="off" value="${h(brandQuery)}"><div class="brand-list">${brands.map(b=>`<label class="check-row" data-brand-row="${h(normalize(b))}" ${normalize(b).includes(normalize(brandQuery))?'':'hidden'}><input type="checkbox" data-brand="${h(b)}" ${filters.brands.includes(b)?'checked':''}><span>${h(b)}</span></label>`).join('')}</div><p class="brand-search-empty" role="status" ${brands.some(b=>normalize(b).includes(normalize(brandQuery)))?'hidden':''}>Производитель не найден. Попробуйте другое название.</p></section>
 <section class="filter-section"><h3>Цена за штуку, ₽</h3><div class="price-inputs"><input type="number" inputmode="numeric" data-filter="min" min="0" placeholder="От" value="${h(filters.min)}" aria-label="Минимальная цена"><span>—</span><input type="number" inputmode="numeric" data-filter="max" min="0" placeholder="До" value="${h(filters.max)}" aria-label="Максимальная цена"></div></section><section class="filter-section"><h3>Ваши пожелания</h3>${['tires','wheels'].includes(filters.kind)&&!filters.staggered?checkbox('inSet','Комплект из 4 штук'):''}${filters.kind==='tires'&&['','passenger'].includes(filters.category)?checkbox('xl','Усиленные XL')+checkbox('runflat','RunFlat'):''}<label class="field"><span>Количество от, шт.</span><input type="number" inputmode="numeric" min="1" max="20" data-filter="minStock" value="${h(filters.minStock)}"></label></section><button class="btn btn-primary filter-done" data-action="close-filters">Показать варианты</button></aside>`;
}
function productCard(p){const o=effectiveOffer(p,filters.inSet?4:1),set=['tires','wheels'].includes(p.kind)?effectiveOffer(p,4):null,fav=favorites.includes(p.id),cmp=compare.includes(p.id);const label=p.kind==='tires'?seasons[p.season]:p.kind==='tubes'?'Камера':categoryNames[p.kind]||'Колёсный диск';return `<article class="product-card"><div class="product-image"><span class="product-tag">${icon(p.kind==='tires'&&p.season==='winter'?'snow':p.kind==='tires'&&p.season==='summer'?'sun':'wheel')}${h(label)}</span><div class="product-actions"><button class="icon-btn ${fav?'selected':''}" data-action="favorite" data-id="${p.id}" aria-label="Избранное ${h(p.model)}" aria-pressed="${fav}">${icon('heart')}</button><button class="icon-btn ${cmp?'selected':''}" data-action="compare" data-id="${p.id}" aria-label="Сравнить ${h(p.model)}" aria-pressed="${cmp}">${icon('compare')}</button></div><button class="product-open product-visual" data-action="detail" data-id="${p.id}" aria-label="Подробнее: ${h(p.brand+' '+p.model)}"><img src="${h(imageUrl(p.image))}" alt="${h(p.brand+' '+p.model)}" width="400" height="400" loading="lazy" referrerpolicy="no-referrer"></button></div><div class="product-info"><p class="product-brand">${h(p.brand)}</p><h3><button class="product-title" data-action="detail" data-id="${p.id}">${h(p.model)}</button></h3><p class="product-size">${h(formatSize(p))}</p><p class="product-meta">${p.kind==='tires'?h((p.loadIndex||'')+(p.speedIndex||'')+(p.xl?' · XL':'')+(p.studded===true?' · Шипованные':p.studded===false?' · Без шипов':'')):p.kind==='wheels'?h('ET '+p.et+' · DIA '+p.dia+' · '+p.color):''}</p><div class="stock-row ${o?'':'no-stock'}">${icon(o?'check':'pin')}<span>${o?'В наличии':'Уточнить наличие'}</span></div><div class="product-price"><strong>${o?money(o.price):'По запросу'}</strong>${o?'<span>/ шт.</span>':''}</div><div class="card-bottom"><div class="set-price">${set?'Комплект 4 шт.<b>'+money(set.price*4)+'</b>':'Выберите количество'}</div><button class="btn btn-primary btn-small" data-action="add" data-id="${p.id}" data-quantity="${set?4:1}" ${o?'':'disabled'}>${icon('plus')} ${set?'4 шт.':'1 шт.'}</button></div></div></article>`;}
function chips(){const names={category:'Категория',width:'Ширина',profile:'Профиль',diameter:'Диаметр',pcd:'PCD',wheelWidth:'Ширина J',et:'ET',dia:'DIA',season:'Сезон',q:'Поиск',min:'От',max:'До',inSet:'Комплект',winterType:'Тип зимних шин',xl:'XL',runflat:'RunFlat'};return (activeVehicle?`<button class="filter-chip vehicle-chip" data-action="clear-vehicle">${icon('car')} ${h(activeVehicle.label)} ${icon('close')}</button>`:'')+Object.entries(names).filter(([k])=>filters[k]).map(([k,n])=>`<button class="filter-chip active-filter" data-action="remove-filter" data-key="${k}">${h(typeof filters[k]==='boolean'?n:categoryNames[filters[k]]||seasons[filters[k]]||(k==='winterType'?winterTypes.find(([v])=>v===filters[k])?.[1]:null)||n+': '+filters[k])} ${icon('close')}</button>`).join('')+filters.brands.map(b=>`<button class="filter-chip" data-action="remove-brand" data-brand="${h(b)}">${h(b)} ${icon('close')}</button>`).join('');}
function renderCatalog(favoriteOnly=false){const found=filterProducts(products,{...effectiveFilters(),onlyFavorites:favoriteOnly},{favorites});const pages=Math.max(1,Math.ceil(found.length/12));page=Math.min(page,pages);main.innerHTML=categories()+(favoriteOnly?heading('Избранное'):`<div class="discovery">${hero()}${selector()}</div>`)+`<div class="catalog-layout">${sidebar()}<section class="catalog-results"><div class="catalog-toolbar"><h2>${h(filters.category?categoryNames[filters.category]:filters.kind==='tires'?'Шины для вашего маршрута':filters.kind==='wheels'?'Диски, которые меняют образ':categoryNames[filters.kind]||'Каталог')}</h2><button class="btn btn-ghost btn-small mobile-filter-btn" data-action="open-filters" aria-controls="filters" aria-expanded="false">${icon('filter')}Фильтры</button><label class="sort-label"><span>Сортировать</span><select data-filter="sort" class="sort-select" aria-label="Сортировка">${[['recommended','Рекомендуемые'],['price-up','Сначала дешевле'],['price-down','Сначала дороже']].map(([v,l])=>`<option value="${v}"${selected(filters.sort,v)}>${l}</option>`).join('')}</select></label></div><form id="search-form" class="search-wrap">${icon('search')}<input name="q" type="search" aria-label="Поиск по модели или размеру" placeholder="Бренд, модель шины, размер или артикул" value="${h(filters.q)}"><button class="text-link">Найти</button></form><div class="active-filters">${chips()}</div>${filters.staggered?renderStaggered(found):found.length?`<div class="product-grid">${found.slice((page-1)*12,page*12).map(productCard).join('')}</div><nav class="pagination" aria-label="Страницы каталога">${paginationPages(page,pages).map(n=>n===null?'<span>…</span>':`<button data-action="page" data-page="${n}" class="${page===n?'active':''}" ${page===n?'aria-current="page"':''}>${n}</button>`).join('')}</nav>`:empty('Попробуем другой вариант','Измените параметры или снимите часть фильтров.')}<p class="catalog-footnote">Перед оформлением поможем проверить совместимость и рассчитать доставку.</p></section></div>`;void refreshVisiblePrices(found.slice((page-1)*12,page*12));}
const detailCache=new Map();
function detailCharacteristics(p,attributes=[]){
 const base=[['Бренд',p.brand],['Модель',p.model],['Артикул',p.sku],['Размер',formatSize(p)]];
 if(p.kind==='tires')base.push(['Сезон',seasons[p.season]],['Индекс нагрузки',p.loadIndex],['Индекс скорости',p.speedIndex],['Шипы',p.studded==null?'Нет данных':p.studded?'Да':'Нет'],['Усиленные XL',p.xl==null?'Нет данных':p.xl?'Да':'Нет'],['RunFlat',p.runflat==null?'Нет данных':p.runflat?'Да':'Нет']);
 if(p.kind==='wheels')base.push(['Вылет ET',p.et],['Центральное отверстие DIA',p.dia],['PCD',p.pcd],['Цвет',p.color]);
 const map=new Map(base.filter(([,v])=>v!==undefined&&v!==null&&v!==''));
 for(const a of [...(p.attributes||[]),...attributes])map.set(a.label,a.value);
 // A brand's home country is not the country of manufacture of this product.
 // Only an explicit, verified per-product attribute may replace this notice.
 const country=map.get('Страна изготовления');
 const countryMissing=typeof country!=='string'||!country.trim()||['-','—','нет данных','unknown','n/a'].includes(country.trim().toLowerCase());
 if(countryMissing)map.set('Страна изготовления','Уточняется перед подтверждением заказа');
 if(p.kind==='tires')for(const label of ['Шумность','Сцепление','Комфорт','Устойчивость к аквапланированию','Индекс износостойкости'])if(!map.has(label))map.set(label,'Нет данных');
 return `<dl class="technical-grid">${[...map].map(([label,value])=>`<div><dt>${h(label)}</dt><dd class="${value==='Нет данных'||(label==='Страна изготовления'&&countryMissing)?'missing-attribute':''}">${h(value)}</dd></div>`).join('')}</dl>`;
}
async function renderDetail(id){
 const p=byId.get(id);if(!p)return;
 const set=['tires','wheels'].includes(p.kind)?effectiveOffer(p,4):null,o=set||effectiveOffer(p),cached=detailCache.get(id);
 showDialog(p.brand+' '+p.model,`<div class="detail-grid"><div class="detail-image"><img src="${h(imageUrl(p.image))}" alt="${h(p.brand+' '+p.model)}" width="400" height="400"></div><div><p class="product-brand">${h(p.brand)}</p><h2>${h(p.model)}</h2><p class="detail-size">${h(formatSize(p))}</p><p>${h(p.description)}</p><p class="muted">Артикул ${h(p.sku)}</p><div class="detail-price">${o?money(o.price):'По запросу'}</div><button class="btn btn-primary" data-action="add" data-id="${p.id}" data-quantity="${set?4:1}" ${o?'':'disabled'}>Добавить ${set?'комплект':'в корзину'} ${icon('plus')}</button></div></div><section class="product-technical"><h3>Характеристики</h3><div id="technical-characteristics">${detailCharacteristics(p,cached||[])}</div><p class="technical-status" id="technical-status" role="status">${portal&&!cached?wheelSpinner('Загружаем характеристики'):''}</p></section>`);
 dialog.dataset.productId=id;
 if(!portal||cached)return;
 try{
  const r=await fetch('/api/products/'+encodeURIComponent(id)+'/details',{signal:AbortSignal.timeout(65000)});
  if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.attributes))throw Error();
  detailCache.set(id,data.attributes);
  if(dialog.open&&dialog.dataset.productId===id){$('#technical-characteristics').innerHTML=detailCharacteristics(p,data.attributes);$('#technical-status').textContent='';}
 }catch{if(dialog.open&&dialog.dataset.productId===id)$('#technical-status').textContent='Дополнительные сведения сейчас недоступны. Поможем уточнить их при подборе.';}
}
function persistCart(){save('cart',cart);counts();}
function add(id,amount){const p=byId.get(id);if(!p)return;const old=cart.find(l=>l.id===id),quantity=(old?.quantity||0)+amount;if(quantity>20||!effectiveOffer(p,quantity)){toast('Недостаточно товара на одном складе. Измените количество.');return;}if(old)old.quantity=quantity;else cart.push({id,quantity});persistCart();toast('Добавлено в корзину');}
function renderCart(){const t=cartTotals(cart,products);main.innerHTML=heading('Ваш комплект')+(cart.length?`<div class="cart-layout"><section class="cart-items">${t.items.map(l=>`<article class="cart-item"><img src="${h(imageUrl(l.product.image))}" alt="${h(l.product.model)}" width="120" height="120"><div><p class="product-brand">${h(l.product.brand)}</p><h2>${h(l.product.model)}</h2><p>${h(formatSize(l.product))}</p><span class="warehouse-label">${l.unavailable?'Уточните наличие':h(l.offer.warehouse)}</span><div class="quantity-control"><button data-action="quantity" data-id="${l.id}" data-delta="-1" aria-label="Уменьшить">−</button><span>${l.quantity}</span><button data-action="quantity" data-id="${l.id}" data-delta="1" aria-label="Увеличить">+</button></div></div><div class="cart-item-price"><strong>${l.unavailable?'По запросу':money(l.subtotal)}</strong><button class="text-link" data-action="remove-cart" data-id="${l.id}">Удалить</button></div></article>`).join('')}<button class="text-link" data-action="clear-cart">Очистить корзину</button></section><aside class="cart-summary"><span class="eyebrow">ВАШ ВЫБОР</span><h2>Комплект готов</h2><div class="summary-total">${money(t.total)}</div><p>Стоимость доставки рассчитаем с учётом вашего города.</p>${portal?`<button class="btn btn-primary full" data-action="checkout" ${t.issues.length?'disabled':''}>Оформить заказ ${icon('arrow')}</button>`:'<a class="btn btn-primary full" href="tel:88003013688">Обсудить заказ</a>'}<button class="btn btn-ghost full" data-action="copy-quote" ${t.issues.length?'disabled':''}>Копировать подборку</button>${portal?`<button class="btn btn-ghost full" data-action="share-quote" ${t.issues.length?'disabled':''}>Ссылка на подборку ↗</button>`:''}<button class="btn btn-ghost full" data-action="download-quote" ${t.issues.length?'disabled':''}>Сохранить подбор</button><p class="form-hint">Менеджер подтвердит наличие и совместимость перед оформлением.</p></aside></div>`:empty('Соберите свой комплект','Добавьте понравившиеся шины или диски из каталога.'));}
function renderCompare(){const rows=compare.map(id=>byId.get(id));main.innerHTML=heading('Сравнение')+(rows.length?`<div class="comparison-scroll"><table class="compare-table"><thead><tr><th>Ваш выбор</th>${rows.map(p=>`<th><img src="${h(imageUrl(p.image))}" width="160" height="160" alt="${h(p.model)}"><h2>${h(p.brand+' '+p.model)}</h2><button class="text-link" data-action="compare" data-id="${p.id}">Убрать</button></th>`).join('')}</tr></thead><tbody>${[['Размер',p=>formatSize(p)],['Цена за штуку',p=>effectiveOffer(p)?money(effectiveOffer(p).price):'По запросу'],['Комплект 4 шт.',p=>effectiveOffer(p,4)?money(effectiveOffer(p,4).price*4):'Уточнить'],['Сезон',p=>seasons[p.season]||'—'],['Артикул',p=>p.sku]].map(([label,get])=>`<tr><th>${h(label)}</th>${rows.map(p=>`<td>${h(get(p))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('Выберите, что сравнить','Добавьте до четырёх моделей кнопкой сравнения на карточках.'));}
function renderGarage(){mode='car';main.innerHTML=heading('Ваш автомобиль')+`<div class="vehicle-intro"><span class="eyebrow">ТОЧНАЯ ПОСАДКА</span><h2>От модели автомобиля<br>к подходящему комплекту.</h2><p>Укажите марку, модель, годы выпуска и модификацию.</p></div>`+selector();}
function renderGuide(){main.innerHTML=heading('Поможем выбрать')+`<div class="guide-grid">${[['01','Начните с автомобиля','Марка и модель — первый шаг. Год выпуска и модификация помогают учесть особенности комплектации.'],['02','Проверьте размеры','Сверьте размер шины с руководством автомобиля. Для диска важны диаметр, ширина, PCD, вылет ET и отверстие DIA.'],['03','Выберите свой сезон','Учитывайте температуру, дороги и привычный стиль вождения. Не забудьте индексы нагрузки и скорости.'],['04','Соберите комплект','Проверьте количество, совместимость передней и задней оси и условия доставки вместе с менеджером.']].map(([n,t,p])=>`<article class="guide-card"><span class="guide-number">${n}</span><h2>${t}</h2><p>${p}</p></article>`).join('')}</div>`;}
async function vehicleFetch(stage){const serial=++vehicleRequest;vehicle.busy=true;vehicle.error='';render();const [begin,end]=(vehicle.years||'0:0').split(':');try{const params=new URLSearchParams({make:vehicle.make,model:vehicle.model,begin,end,modification:vehicle.modification});const r=await withLoading(()=>fetch('/api/fitment/'+stage+'?'+params,{signal:AbortSignal.timeout(65000)}));if(!r.ok)throw new Error();const d=await r.json();if(serial!==vehicleRequest)return;if(stage==='makes')vehicle.makes=d.items;else if(stage==='models')vehicle.models=d.items;else if(stage==='years')vehicle.ranges=d.items;else if(stage==='modifications')vehicle.modifications=d.items;else{activeVehicle={ids:new Set(d.productIds),label:vehicle.make+' '+vehicle.model+' · '+vehicle.modification};filters=parseFilters('kind='+filters.kind);location.hash='catalog';}}catch{if(serial===vehicleRequest)vehicle.error='Не удалось загрузить варианты. Попробуйте ещё раз или обратитесь к менеджеру.';}finally{if(serial===vehicleRequest){vehicle.busy=false;render();if(stage==='products')$('.catalog-results')?.scrollIntoView({behavior:'smooth'});}}}
function openCar(){mode='car';render();$('#selector')?.scrollIntoView({behavior:'smooth',block:'center'});if(portal&&!vehicle.makes.length&&!vehicle.busy)vehicleFetch('makes');}
function render(){document.body.classList.remove('filters-open');if(dialog.open)dialog.close();counts();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route()));if(['delivery','payment','order-status','returns','contacts'].includes(route()))renderShopPage(route(),main);else if(route()==='cart')renderCart();else if(route()==='compare')renderCompare();else if(route()==='garage')renderGarage();else if(route()==='guide')renderGuide();else if(route()==='manager'){location.href='./manager/';return;}else renderCatalog(route()==='favorites');const pageTitle={cart:'Ваш комплект',compare:'Сравнение',garage:'Подбор по автомобилю',guide:'Помощь',favorites:'Избранное'}[route()];document.title=pageTitle?pageTitle+' — Шины и диски':'Шины и диски — подбор и заказ';}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const {action,id,value}=b.dataset;
if(action==='close-dialog')dialog.close();
if(action==='detail')renderDetail(id);
if(action==='add')add(id,Number(b.dataset.quantity)||1);
if(action==='favorite'){if(!byId.has(id))return;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save('favorites',favorites);render();}
if(action==='compare'){if(!byId.has(id))return;if(compare.includes(id))compare=compare.filter(x=>x!==id);else{if(compare.length>=4){toast('Можно сравнить до четырёх моделей');return;}if(compare.length&&byId.get(compare[0]).kind!==byId.get(id).kind){toast('Выберите товары одной категории');return;}compare.push(id);}save('compare',compare);render();}
if(action==='segment'||action==='category'){brandQuery='';pairChoice={front:null,rear:null};mode='size';activeVehicle=null;filters=parseFilters('kind='+b.dataset.kind);filters.category=b.dataset.category||'';sync();}
if(action==='mode'){mode=value;if(mode==='car')openCar();else render();}
if(action==='hero-car')openCar();
if(action==='vehicle-search')vehicleFetch('products');
if(action==='clear-vehicle'){activeVehicle=null;sync();}
if(action==='choose-axle'){pairChoice[b.dataset.axle]=id;if(b.dataset.axle==='front')pairChoice.rear=null;render();}
if(action==='add-axles'){const ids=[pairChoice.front,pairChoice.rear];if(!ids.every(x=>byId.has(x)))return;const quantities=new Map();for(const x of ids)quantities.set(x,(quantities.get(x)||0)+2);if([...quantities].some(([x,n])=>!effectiveOffer(byId.get(x),(cart.find(l=>l.id===x)?.quantity||0)+n))){toast('Недостаточно товара для выбранного комплекта.');return;}for(const [x,n] of quantities)add(x,n);location.hash='cart';}
if(action==='checkout'){await startCheckout(cart.map(l=>({productId:l.id,quantity:l.quantity})),()=>{cart=[];persistCart();});}
if(action==='season'){filters=setSeason(filters,value);pairChoice={front:null,rear:null};sync();}
if(action==='winter-type'){filters.winterType=value;filters.studded=false;pairChoice={front:null,rear:null};sync();}
if(action==='reset'){brandQuery='';const currentCategory=filters.category;filters=parseFilters('kind='+filters.kind);filters.category=currentCategory;activeVehicle=null;sync();}
if(action==='remove-filter'){if(b.dataset.key==='season')filters=setSeason(filters,'');else filters[b.dataset.key]='';pairChoice={front:null,rear:null};sync();}
if(action==='remove-brand'){filters.brands=filters.brands.filter(v=>v!==b.dataset.brand);sync();}
if(action==='page'){page=Number(b.dataset.page);render();$('.catalog-toolbar')?.scrollIntoView({behavior:'smooth'});}
if(action==='show-results')$('.catalog-results')?.scrollIntoView({behavior:'smooth'});
if(action==='open-filters')setFiltersOpen(true);
if(action==='close-filters')setFiltersOpen(false);
if(action==='clear-cart'){cart=[];persistCart();render();}
if(action==='remove-cart'){cart=cart.filter(l=>l.id!==id);persistCart();render();}
if(action==='quantity'){const l=cart.find(l=>l.id===id);if(!l)return;const n=l.quantity+Number(b.dataset.delta);if(n<1||n>20||!effectiveOffer(byId.get(id),n)){toast('Проверьте доступное количество');return;}l.quantity=n;persistCart();render();}
if(action==='copy-quote'){const t=cartTotals(cart,products);if(t.issues.length)return;try{await copyText(selectionText({total:t.total,lines:t.items.map(l=>({name:l.product.brand+' '+l.product.model,description:formatSize(l.product),sku:l.product.sku,price:l.offer.price,quantity:l.quantity,subtotal:l.subtotal}))}));toast('Подборка скопирована — вставьте её в сообщение клиенту.');}catch(error){toast(error.message);}}
if(action==='share-quote'){b.disabled=true;try{const result=await createSelection(cart.map(l=>({productId:l.id,quantity:l.quantity})));const url=new URL(result.url,location.origin).href;showDialog('Ваша подборка',`<p>Ссылка действует 7 дней. Цены и наличие уточняются при оформлении.</p><input id="selection-link" value="${h(url)}" readonly aria-label="Ссылка на подборку"><textarea id="selection-text" rows="9" readonly aria-label="Текст подборки">${h(selectionText(result,url))}</textarea><div class="share-actions"><button class="btn btn-primary" data-action="copy-shared-link">Копировать ссылку</button><button class="btn btn-ghost" data-action="copy-shared-text">Копировать текст</button>${navigator.share?'<button class="btn btn-ghost" data-action="native-share">Поделиться…</button>':''}</div>`);}catch(error){toast(error.message);}finally{b.disabled=false;}}
if(action==='copy-shared-link'||action==='copy-shared-text'){try{await copyText($(action==='copy-shared-link'?'#selection-link':'#selection-text').value);toast('Скопировано');}catch(error){toast(error.message);}}
if(action==='native-share'){try{await navigator.share({title:'Подборка шин и дисков',url:$('#selection-link').value});}catch(error){if(error.name!=='AbortError')toast('Скопируйте ссылку кнопкой рядом.');}}
if(action==='download-quote'){const t=cartTotals(cart,products);if(t.issues.length)return;const data={brand:'Шины и диски',createdAt:new Date().toISOString(),total:t.total,lines:t.items.map(l=>({sku:l.product.sku,name:l.product.brand+' '+l.product.model,size:formatSize(l.product),quantity:l.quantity,price:l.offer.price})),notice:'Подбор для обсуждения с менеджером. Доставка рассчитывается отдельно.'};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='podbor-shin-i-diskov.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.filter){if(['width','profile','diameter','rearWidth','rearProfile','rearDiameter','sameModel','staggered','season','winterType'].includes(el.dataset.filter))pairChoice={front:null,rear:null};if(el.dataset.filter==='season')filters=setSeason(filters,el.value);else filters[el.dataset.filter]=el.type==='checkbox'?el.checked:el.value;sync();}if(el.dataset.brand){pairChoice={front:null,rear:null};filters.brands=el.checked?[...new Set([...filters.brands,el.dataset.brand])]:filters.brands.filter(b=>b!==el.dataset.brand);sync();}if(el.dataset.vehicle){vehicleRequest++;vehicle.busy=false;activeVehicle=null;const k=el.dataset.vehicle;vehicle[k]=el.value;if(k==='make'){vehicle.model='';vehicle.years='';vehicle.modification='';vehicle.models=[];vehicle.ranges=[];vehicle.modifications=[];if(el.value)vehicleFetch('models');else render();}if(k==='model'){vehicle.years='';vehicle.modification='';vehicle.ranges=[];vehicle.modifications=[];if(el.value)vehicleFetch('years');else render();}if(k==='years'){vehicle.modification='';vehicle.modifications=[];if(el.value)vehicleFetch('modifications');else render();}if(k==='modification')render();}});
document.addEventListener('input',e=>{if(e.target.id==='brand-search'){brandQuery=e.target.value;const q=normalize(brandQuery);let visible=0;document.querySelectorAll('[data-brand-row]').forEach(el=>{el.hidden=!el.dataset.brandRow.includes(q);if(!el.hidden)visible++;});$('.brand-search-empty').hidden=visible>0;}});
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();filters.q=new FormData(e.target).get('q').trim();sync();}});
document.addEventListener('error',e=>{const img=e.target;if(img.tagName==='IMG'&&!img.dataset.fallback){img.dataset.fallback='true';img.src=imageUrl('assets/product-unavailable.svg');img.alt='Изображение уточняется';}},true);
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
window.addEventListener('hashchange',()=>{if(['catalog','favorites'].includes(route())){filters=parseFilters(location.hash.split('?')[1]);page=1;}render();if(route()==='garage'&&portal&&!vehicle.makes.length&&!vehicle.busy)vehicleFetch('makes');window.scrollTo({top:0});});
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));render();if(route()==='garage'&&portal)vehicleFetch('makes');

// The whole card opens details, while its action buttons keep their own behavior.
document.addEventListener('click',event=>{const card=event.target.closest('.product-card');if(card&&!event.target.closest('button,a,input,select,textarea')){const detail=card.querySelector('[data-action="detail"]');if(detail)renderDetail(detail.dataset.id);}});

function rearFields(){return `<div class="rear-axle-fields"><span class="eyebrow">ЗАДНЯЯ ОСЬ · ПЕРЕДНЯЯ УКАЗАНА ВЫШЕ</span><div class="selector-fields">${[['width','Ширина'],['profile','Профиль'],['diameter','Диаметр']].map(([k,label])=>{const key='rear'+k[0].toUpperCase()+k.slice(1);const f={...filters,staggered:false,width:filters.rearWidth,profile:filters.rearProfile,diameter:filters.rearDiameter};return `<label class="field"><span>${label}</span><select data-filter="${key}" aria-label="Задняя ось: ${label}"><option value="">Любой</option>${facetOptions(products,f,k).map(v=>`<option value="${h(v)}"${selected(filters[key],v)}>${h(v)}</option>`).join('')}</select></label>`;}).join('')}</div><label class="check-row"><input type="checkbox" data-filter="sameModel" ${filters.sameModel?'checked':''}><span>Одинаковые бренд и модель на обеих осях</span></label></div>`;}
function renderStaggered(found){const selectedFront=byId.get(pairChoice.front);let rear=found.filter(p=>matchesAxle(p,filters,'rear'));if(filters.sameModel&&selectedFront)rear=rear.filter(p=>pairKey(p)===pairKey(selectedFront));const front=found.filter(p=>matchesAxle(p,filters,'front'));const complete=['width','profile','diameter','rearWidth','rearProfile','rearDiameter'].every(k=>filters[k]);return `<div class="axle-summary"><div><strong>Комплект 2 + 2</strong><span>Передняя ось + задняя ось</span></div><button class="btn btn-primary" data-action="add-axles" ${complete&&pairChoice.front&&pairChoice.rear?'':'disabled'}>Добавить комплект</button></div>${!complete?'<p class="selection-note">Укажите все три размера для каждой оси, затем выберите две позиции.</p>':''}<div class="axle-results">${[['front','Передняя ось',front],['rear','Задняя ось',rear]].map(([axle,label,rows])=>`<section><h3>${label} <small>2 шт.</small></h3><div class="axle-list">${rows.slice(0,30).map(p=>{const o=effectiveOffer(p,2);return `<article class="axle-item ${pairChoice[axle]===p.id?'chosen':''}"><button class="axle-photo" data-action="detail" data-id="${h(p.id)}"><img src="${h(imageUrl(p.image))}" alt="${h(p.model)}" loading="lazy" width="74" height="74"></button><div><b>${h(p.brand+' '+p.model)}</b><span>${h(formatSize(p))}</span><small>Арт. ${h(p.sku)}</small><strong>${o?money(o.price*2)+' / 2 шт.':'Уточнить цену'}</strong></div><button class="btn btn-small" data-action="choose-axle" data-axle="${axle}" data-id="${h(p.id)}" ${o?'':'disabled'}>${pairChoice[axle]===p.id?'Выбрано':'Выбрать'}</button></article>`;}).join('')||'<p class="selection-note">Вариантов пока нет. Измените размеры или выбор модели.</p>'}</div>${rows.length>30?'<p class="form-hint">Уточните бренд и модель, чтобы сузить выбор.</p>':''}</section>`).join('')}</div>`;}

async function refreshVisiblePrices(visible){
 if(!portal||priceLoading)return;const ids=visible.filter(p=>!p.offers.length&&!priceChecked.has(p.id)).map(p=>p.id);if(!ids.length)return;
 ids.forEach(id=>priceChecked.add(id));priceLoading=true;const view=location.hash;
 try{const r=await withLoading(()=>fetch('/api/shop/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids}),signal:AbortSignal.timeout(90000)}));if(!r.ok)return;const data=await r.json();for(const p of data.items||[]){const existing=byId.get(p.id);if(existing)Object.assign(existing,p);}if(location.hash===view&&['catalog','favorites'].includes(route())&&!dialog.open)renderCatalog(route()==='favorites');}catch{}finally{priceLoading=false;}
}

// Keep the mobile drawer keyboard-accessible after filter updates.
document.addEventListener('keydown',event=>{const drawer=$('#filters.open');if(!drawer)return;if(event.key==='Escape'){event.preventDefault();setFiltersOpen(false);return;}if(event.key!=='Tab')return;const controls=[...drawer.querySelectorAll('button,input,select,a[href]')].filter(el=>!el.disabled&&!el.closest('[hidden]'));const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}});
window.addEventListener('resize',()=>{if(window.innerWidth>850)setFiltersOpen(false,false);},{passive:true});
