import {money,escapeHTML as h,effectiveOffer,formatSize,filterProducts,facetOptions,cartTotals,parseFilters,serializeFilters,paginationPages} from './domain.js';
const $=(s,r=document)=>r.querySelector(s), main=$('#main'), dialog=$('#dialog');
const catalog=window.IMKONEX_DATA, products=catalog.products, byId=new Map(products.map(p=>[p.id,p]));
const portal=window.IMKONEX_CONFIG?.portal===true;
const paths={heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',compare:'M5 20V10M12 20V4M19 20v-7',bag:'M5 7h14l1 14H4L5 7Zm3 0V5a4 4 0 0 1 8 0v2',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',close:'m6 6 12 12M6 18 18 6',arrow:'M4 12h16m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14',minus:'M5 12h14',check:'m5 12 4 4L19 6',car:'m3 10 2-6h14l2 6M2 10h20v9H2v-9Zm3 9v3m14-3v3M5 14h3m8 0h3',wheel:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0ZM12 2v7m0 6v7M2 12h7m6 0h7M9 12a3 3 0 1 0 6 0 3 3 0 0 0-6 0Z',snow:'M12 2v20M3 7l18 10M3 17 21 7M8 4l4 3 4-3M8 20l4-3 4 3',sun:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8ZM12 1v3m0 16v3M1 12h3m16 0h3',filter:'M4 7h16M4 17h16M8 4v6m8 4v6',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15',truck:'M1 5h13v12H1V5Zm13 4h4l4 5v3h-8M7 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0ZM21 18a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z'};
const icon=n=>`<svg class="icon" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.wheel}"/></svg>`;
const imageUrl=p=>window.IMKONEX_IMAGE_MAP?.[p]||(p.startsWith('https://')?p:'./'+p);
const memory=new Map(),prefix='imx:snapshot:';
function load(k,def){try{return memory.get(k)??JSON.parse(localStorage.getItem(prefix+k))??def;}catch{return memory.get(k)??def;}}
function save(k,v){memory.set(k,v);try{localStorage.setItem(prefix+k,JSON.stringify(v));}catch{}}
const validIds=items=>Array.isArray(items)?[...new Set(items.filter(id=>byId.has(id)))]:[];
let favorites=validIds(load('favorites',[])),compare=validIds(load('compare',[])).slice(0,4);
let cart=load('cart',[]);cart=Array.isArray(cart)?cart.filter(l=>byId.has(l.id)&&Number.isInteger(l.quantity)&&l.quantity>0&&l.quantity<=20):[];
let filters=parseFilters(location.hash.split('?')[1]),page=1,mode='size',activeVehicle=null,toastTimer,vehicleRequest=0;
const vehicle={make:'',model:'',years:'',modification:'',makes:[],models:[],ranges:[],modifications:[],busy:false,error:''};
const seasons={summer:'Летние',winter:'Зимние',allseason:'Всесезонные',unknown:'Сезон уточняется'};
const categoryNames={passenger:'Легковые и SUV',truck:'Грузовые и коммерческие',special:'Спецтехника',moto:'Мото и квадроциклы',other:'Другие шины',tubes:'Камеры',wheels:'Диски'};
const route=()=>location.hash.slice(1).split('?')[0]||'catalog';
const selected=(a,b)=>String(a)===String(b)?' selected':'';
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3400);}
function counts(){for(const [key,value] of [['favorites',favorites.length],['compare',compare.length],['cart',cart.reduce((s,l)=>s+l.quantity,0)]]){const el=$('#'+key+'-count');el.textContent=value;el.hidden=!value;}}
function heading(title){return `<div class="breadcrumb"><a href="#catalog">Главная</a><span>/</span><span>${h(title)}</span></div><div class="page-heading"><h1>${h(title)}</h1></div>`;}
function empty(title,note){return `<div class="empty-state">${icon('wheel')}<h2>${h(title)}</h2><p>${h(note)}</p><a href="#catalog" class="btn btn-primary">В каталог ${icon('arrow')}</a></div>`;}
function showDialog(title,html){$('#dialog-content').innerHTML=`<div class="dialog-header"><h2 id="dialog-title">${h(title)}</h2><button class="icon-btn" data-action="close-dialog" aria-label="Закрыть">${icon('close')}</button></div><div class="dialog-body">${html}</div>`;dialog.showModal();}
function sync(){page=1;const hash='#'+(route()==='favorites'?'favorites':'catalog')+'?'+serializeFilters(filters);try{history.replaceState(null,'',hash);}catch{}render();}
function effectiveFilters(){return {...filters,...(activeVehicle?{vehicleIds:activeVehicle.ids}:{})};}
function hero(){return `<section class="hero"><div class="hero-copy"><span class="eyebrow">IMKONEX / КОЛЛЕКЦИЯ ДЛЯ ВАШЕГО АВТО</span><h1>Уверенность<br>в каждом<br><em>повороте.</em></h1><p>Шины и диски, которые подходят<br>вашему автомобилю и вашему стилю.</p><button class="btn btn-lime" data-action="hero-car">Подобрать для автомобиля ${icon('arrow')}</button><span class="hero-caption">Точный подбор · внимание к деталям</span></div><div class="hero-visual" aria-hidden="true"><span class="hero-orbit"></span><span class="hero-lettering">THE PERFECT<br>FIT.</span><img class="hero-tire" src="./assets/products/R5019.png" alt=""><img class="hero-wheel" src="./assets/products/WHS121894.png" alt=""><div class="hero-stamp">01 — КОЛЁСА С ХАРАКТЕРОМ</div></div></section>`;}
function categories(){const available=new Set(products.map(p=>p.vehicleCategory).filter(Boolean));return `<nav class="segment-nav" aria-label="Назначение"><button data-action="segment" data-kind="tires" data-category="" class="${filters.kind==='tires'&&!filters.category?'active':''}">Все шины</button>${['passenger','truck','special','moto'].filter(c=>available.has(c)).map(c=>`<button data-action="segment" data-kind="tires" data-category="${c}" class="${filters.category===c?'active':''}">${h(categoryNames[c])}</button>`).join('')}<button data-action="segment" data-kind="wheels" data-category="" class="${filters.kind==='wheels'?'active':''}">Диски</button>${products.some(p=>p.kind==='tubes')?`<button data-action="segment" data-kind="tubes" data-category="" class="${filters.kind==='tubes'?'active':''}">Камеры</button>`:''}</nav>`;}
function field(key,label){const values=facetOptions(products,effectiveFilters(),key);return `<label class="field"><span>${h(label)}</span><select data-filter="${key}" name="${key}" aria-label="${h(label)}"><option value="">Любой</option>${values.map(v=>`<option value="${h(v)}"${selected(filters[key],v)}>${h(v)}</option>`).join('')}</select></label>`;}
function vehicleSelect(key,label,values,disabled){return `<label class="field"><span>${h(label)}</span><select data-vehicle="${key}" aria-label="${h(label)}" ${disabled?'disabled':''}><option value="">Выберите</option>${values.map(v=>{const value=typeof v==='string'?v:v.value,label=typeof v==='string'?v:v.label;return `<option value="${h(value)}"${selected(vehicle[key],value)}>${h(label)}</option>`;}).join('')}</select></label>`;}
function vehiclePanel(){if(!portal)return `<div class="vehicle-offline"><div>${icon('car')}<h3>Подберём комплект для вашего автомобиля</h3><p>Назовите марку, модель и год выпуска — мы поможем проверить размеры.</p></div><a class="btn btn-primary" href="tel:88003013688">Связаться с менеджером ${icon('arrow')}</a></div>`;return `<div class="vehicle-fields">${vehicleSelect('make','Марка',vehicle.makes,vehicle.busy&&!vehicle.makes.length)}${vehicleSelect('model','Модель',vehicle.models,!vehicle.make||vehicle.busy)}${vehicleSelect('years','Годы выпуска',vehicle.ranges.map(r=>({value:r.begin+':'+r.end,label:r.begin===r.end?String(r.begin):r.begin+'–'+r.end})),!vehicle.model||vehicle.busy)}${vehicleSelect('modification','Модификация',vehicle.modifications,!vehicle.years||vehicle.busy)}<button class="btn btn-primary" data-action="vehicle-search" ${!vehicle.modification||vehicle.busy?'disabled':''}>${vehicle.busy?'Загружаем…':'Найти комплект'} ${icon('arrow')}</button></div><p class="vehicle-hint" role="status">${h(vehicle.error||(vehicle.busy?'Загружаем варианты…':'Подбор по штатным размерам. Учитывайте комплектацию и установленные тормоза.'))}</p>`;}
function selector(){return `<section id="selector" class="selector"><div class="selector-top"><h2>Найдём ваш комплект</h2><div class="selection-mode" role="group" aria-label="Способ подбора"><button data-action="mode" data-value="size" class="${mode==='size'?'active':''}">По размеру</button><button data-action="mode" data-value="car" class="${mode==='car'?'active':''}">По автомобилю</button></div></div>${mode==='car'?vehiclePanel():`<div class="selector-fields">${filters.kind==='tires'?field('width','Ширина')+field('profile','Профиль')+field('diameter','Диаметр'):filters.kind==='wheels'?field('diameter','Диаметр')+field('wheelWidth','Ширина диска')+field('pcd','Крепёж PCD'):field('diameter','Диаметр камеры')}<button class="btn btn-primary" data-action="show-results">Подобрать ${icon('arrow')}</button></div>`}</section>`;}
function sidebar(){const brands=facetOptions(products,effectiveFilters(),'brands');const checkbox=(key,label)=>`<label class="check-row"><input type="checkbox" data-filter="${key}" ${filters[key]?'checked':''}><span>${label}</span></label>`;return `<aside class="filters sidebar" id="filters"><div class="filter-heading"><h2>Детали подбора</h2><button class="text-link" data-action="reset">Сбросить</button><button class="icon-btn filter-close" data-action="close-filters" aria-label="Закрыть">${icon('close')}</button></div>${filters.kind==='tires'?`<section class="filter-section"><h3>Сезон</h3><div class="season-pills">${[['','Все'],['summer','Лето'],['winter','Зима'],['allseason','Всесезонные']].map(([v,l])=>`<button class="season-btn ${filters.season===v?'active':''}" data-action="season" data-value="${v}">${h(l)}</button>`).join('')}</div></section>`:filters.kind==='wheels'?`<section class="filter-section"><h3>Посадка диска</h3>${field('et','Вылет ET')}${field('dia','Отверстие DIA')}</section>`:''}<section class="filter-section"><h3>Бренд</h3><input id="brand-search" class="brand-search" type="search" placeholder="Найти бренд" aria-label="Найти бренд"><div class="brand-list">${brands.map(b=>`<label class="check-row" data-brand-row="${h(b.toLowerCase())}"><input type="checkbox" data-brand="${h(b)}" ${filters.brands.includes(b)?'checked':''}><span>${h(b)}</span></label>`).join('')}</div></section><section class="filter-section"><h3>Цена за штуку, ₽</h3><div class="price-inputs"><input type="number" data-filter="min" min="0" placeholder="От" value="${h(filters.min)}" aria-label="Минимальная цена"><span>—</span><input type="number" data-filter="max" min="0" placeholder="До" value="${h(filters.max)}" aria-label="Максимальная цена"></div></section><section class="filter-section"><h3>Ваши пожелания</h3>${checkbox('inSet','Комплект из 4 штук')}${filters.kind==='tires'?checkbox('studded','С шипами')+checkbox('xl','Усиленные XL')+checkbox('runflat','RunFlat'):''}</section></aside>`;}
function productCard(p){const o=effectiveOffer(p,filters.inSet?4:1),set=effectiveOffer(p,4),fav=favorites.includes(p.id),cmp=compare.includes(p.id);const label=p.kind==='tires'?seasons[p.season]:p.kind==='tubes'?'Камера':'Колёсный диск';return `<article class="product-card"><div class="product-image"><span class="product-tag">${icon(p.kind==='tires'&&p.season==='winter'?'snow':p.kind==='tires'&&p.season==='summer'?'sun':'wheel')}${h(label)}</span><div class="product-actions"><button class="icon-btn ${fav?'selected':''}" data-action="favorite" data-id="${p.id}" aria-label="Избранное ${h(p.model)}" aria-pressed="${fav}">${icon('heart')}</button><button class="icon-btn ${cmp?'selected':''}" data-action="compare" data-id="${p.id}" aria-label="Сравнить ${h(p.model)}" aria-pressed="${cmp}">${icon('compare')}</button></div><button class="product-open product-visual" data-action="detail" data-id="${p.id}" aria-label="Подробнее: ${h(p.brand+' '+p.model)}"><img src="${h(imageUrl(p.image))}" alt="${h(p.brand+' '+p.model)}" width="400" height="400" loading="lazy" referrerpolicy="no-referrer"></button></div><div class="product-info"><p class="product-brand">${h(p.brand)}</p><h3><button class="product-title" data-action="detail" data-id="${p.id}">${h(p.model)}</button></h3><p class="product-size">${h(formatSize(p))}</p><p class="product-meta">${p.kind==='tires'?h((p.loadIndex||'')+(p.speedIndex||'')+(p.xl?' · XL':'')+(p.studded===true?' · Шипованные':p.studded===false?' · Без шипов':'')):p.kind==='wheels'?h('ET '+p.et+' · DIA '+p.dia+' · '+p.color):''}</p><div class="stock-row ${o?'':'no-stock'}">${icon(o?'check':'pin')}<span>${o?'В наличии':'Уточнить наличие'}</span></div><div class="product-price"><strong>${o?money(o.price):'По запросу'}</strong>${o?'<span>/ шт.</span>':''}</div><div class="card-bottom"><div class="set-price">${set?'Комплект 4 шт.<b>'+money(set.price*4)+'</b>':'Выберите количество'}</div><button class="btn btn-primary btn-small" data-action="add" data-id="${p.id}" data-quantity="${set?4:1}" ${o?'':'disabled'}>${icon('plus')} ${set?'4 шт.':'1 шт.'}</button></div></div></article>`;}
function chips(){const names={category:'Категория',width:'Ширина',profile:'Профиль',diameter:'Диаметр',pcd:'PCD',wheelWidth:'Ширина J',et:'ET',dia:'DIA',season:'Сезон',q:'Поиск',min:'От',max:'До',inSet:'Комплект',studded:'Шипы',xl:'XL',runflat:'RunFlat'};return (activeVehicle?`<button class="filter-chip vehicle-chip" data-action="clear-vehicle">${icon('car')} ${h(activeVehicle.label)} ${icon('close')}</button>`:'')+Object.entries(names).filter(([k])=>filters[k]).map(([k,n])=>`<button class="filter-chip active-filter" data-action="remove-filter" data-key="${k}">${h(typeof filters[k]==='boolean'?n:categoryNames[filters[k]]||seasons[filters[k]]||n+': '+filters[k])} ${icon('close')}</button>`).join('')+filters.brands.map(b=>`<button class="filter-chip" data-action="remove-brand" data-brand="${h(b)}">${h(b)} ${icon('close')}</button>`).join('');}
function renderCatalog(favoriteOnly=false){const found=filterProducts(products,{...effectiveFilters(),onlyFavorites:favoriteOnly},{favorites});const pages=Math.max(1,Math.ceil(found.length/12));page=Math.min(page,pages);main.innerHTML=(favoriteOnly?heading('Избранное'):hero())+categories()+selector()+`<div class="catalog-layout">${sidebar()}<section class="catalog-results"><div class="catalog-toolbar"><h2>${h(filters.category?categoryNames[filters.category]:filters.kind==='tires'?'Шины для вашего маршрута':filters.kind==='wheels'?'Диски, которые меняют образ':'Камеры')}</h2><button class="btn btn-ghost btn-small mobile-filter-btn" data-action="open-filters">${icon('filter')}Фильтры</button><label class="sort-label"><span>Сортировать</span><select data-filter="sort" class="sort-select" aria-label="Сортировка">${[['recommended','Рекомендуемые'],['price-up','Сначала дешевле'],['price-down','Сначала дороже']].map(([v,l])=>`<option value="${v}"${selected(filters.sort,v)}>${l}</option>`).join('')}</select></label></div><form id="search-form" class="search-wrap">${icon('search')}<input name="q" type="search" aria-label="Поиск по модели или размеру" placeholder="Бренд, модель шины, размер или артикул" value="${h(filters.q)}"><button class="text-link">Найти</button></form><div class="active-filters">${chips()}</div>${found.length?`<div class="product-grid">${found.slice((page-1)*12,page*12).map(productCard).join('')}</div><nav class="pagination" aria-label="Страницы каталога">${paginationPages(page,pages).map(n=>n===null?'<span>…</span>':`<button data-action="page" data-page="${n}" class="${page===n?'active':''}" ${page===n?'aria-current="page"':''}>${n}</button>`).join('')}</nav>`:empty('Попробуем другой вариант','Измените параметры или снимите часть фильтров.')}<p class="catalog-footnote">Перед оформлением поможем проверить совместимость и рассчитать доставку.</p></section></div>`;}
function renderDetail(id){const p=byId.get(id);if(!p)return;const o=effectiveOffer(p,4)||effectiveOffer(p);showDialog(p.brand+' '+p.model,`<div class="detail-grid"><div class="detail-image"><img src="${h(imageUrl(p.image))}" alt="${h(p.model)}" width="400" height="400"></div><div><p class="product-brand">${h(p.brand)}</p><h2>${h(p.model)}</h2><p class="detail-size">${h(formatSize(p))}</p><p>${h(p.description)}</p><p class="muted">Артикул ${h(p.sku)}</p><div class="detail-price">${o?money(o.price):'По запросу'}</div><button class="btn btn-primary" data-action="add" data-id="${p.id}" data-quantity="${effectiveOffer(p,4)?4:1}" ${o?'':'disabled'}>Добавить ${effectiveOffer(p,4)?'комплект':'в корзину'} ${icon('plus')}</button><p class="form-hint">Проверьте размеры, нагрузку и комплектацию автомобиля перед покупкой.</p></div></div>`);}
function persistCart(){save('cart',cart);counts();}
function add(id,amount){const p=byId.get(id);if(!p)return;const old=cart.find(l=>l.id===id),quantity=(old?.quantity||0)+amount;if(quantity>20||!effectiveOffer(p,quantity)){toast('Недостаточно товара на одном складе. Измените количество.');return;}if(old)old.quantity=quantity;else cart.push({id,quantity});persistCart();toast('Добавлено в корзину');}
function renderCart(){const t=cartTotals(cart,products);main.innerHTML=heading('Ваш комплект')+(cart.length?`<div class="cart-layout"><section class="cart-items">${t.items.map(l=>`<article class="cart-item"><img src="${h(imageUrl(l.product.image))}" alt="${h(l.product.model)}" width="120" height="120"><div><p class="product-brand">${h(l.product.brand)}</p><h2>${h(l.product.model)}</h2><p>${h(formatSize(l.product))}</p><span class="warehouse-label">${l.unavailable?'Уточните наличие':h(l.offer.warehouse)}</span><div class="quantity-control"><button data-action="quantity" data-id="${l.id}" data-delta="-1" aria-label="Уменьшить">−</button><span>${l.quantity}</span><button data-action="quantity" data-id="${l.id}" data-delta="1" aria-label="Увеличить">+</button></div></div><div class="cart-item-price"><strong>${l.unavailable?'По запросу':money(l.subtotal)}</strong><button class="text-link" data-action="remove-cart" data-id="${l.id}">Удалить</button></div></article>`).join('')}<button class="text-link" data-action="clear-cart">Очистить корзину</button></section><aside class="cart-summary"><span class="eyebrow">ВАШ ВЫБОР</span><h2>Комплект готов</h2><div class="summary-total">${money(t.total)}</div><p>Стоимость доставки рассчитаем с учётом вашего города.</p><a class="btn btn-primary full" href="tel:88003013688">Обсудить заказ ${icon('arrow')}</a><button class="btn btn-ghost full" data-action="download-quote" ${t.issues.length?'disabled':''}>Сохранить подбор</button><p class="form-hint">Менеджер подтвердит наличие и совместимость перед оформлением.</p></aside></div>`:empty('Соберите свой комплект','Добавьте понравившиеся шины или диски из каталога.'));}
function renderCompare(){const rows=compare.map(id=>byId.get(id));main.innerHTML=heading('Сравнение')+(rows.length?`<div class="comparison-scroll"><table class="compare-table"><thead><tr><th>Ваш выбор</th>${rows.map(p=>`<th><img src="${h(imageUrl(p.image))}" width="160" height="160" alt="${h(p.model)}"><h2>${h(p.brand+' '+p.model)}</h2><button class="text-link" data-action="compare" data-id="${p.id}">Убрать</button></th>`).join('')}</tr></thead><tbody>${[['Размер',p=>formatSize(p)],['Цена за штуку',p=>effectiveOffer(p)?money(effectiveOffer(p).price):'По запросу'],['Комплект 4 шт.',p=>effectiveOffer(p,4)?money(effectiveOffer(p,4).price*4):'Уточнить'],['Сезон',p=>seasons[p.season]||'—'],['Артикул',p=>p.sku]].map(([label,get])=>`<tr><th>${h(label)}</th>${rows.map(p=>`<td>${h(get(p))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('Выберите, что сравнить','Добавьте до четырёх моделей кнопкой сравнения на карточках.'));}
function renderGarage(){mode='car';main.innerHTML=heading('Ваш автомобиль')+`<div class="vehicle-intro"><span class="eyebrow">ТОЧНАЯ ПОСАДКА</span><h2>От модели автомобиля<br>к подходящему комплекту.</h2><p>Укажите марку, модель, годы выпуска и модификацию.</p></div>`+selector();}
function renderGuide(){main.innerHTML=heading('Поможем выбрать')+`<div class="guide-grid">${[['01','Начните с автомобиля','Марка и модель — первый шаг. Год выпуска и модификация помогают учесть особенности комплектации.'],['02','Проверьте размеры','Сверьте размер шины с руководством автомобиля. Для диска важны диаметр, ширина, PCD, вылет ET и отверстие DIA.'],['03','Выберите свой сезон','Учитывайте температуру, дороги и привычный стиль вождения. Не забудьте индексы нагрузки и скорости.'],['04','Соберите комплект','Проверьте количество, совместимость передней и задней оси и условия доставки вместе с менеджером.']].map(([n,t,p])=>`<article class="guide-card"><span class="guide-number">${n}</span><h2>${t}</h2><p>${p}</p></article>`).join('')}</div>`;}
async function vehicleFetch(stage){const serial=++vehicleRequest;vehicle.busy=true;vehicle.error='';render();const [begin,end]=(vehicle.years||'0:0').split(':');try{const params=new URLSearchParams({make:vehicle.make,model:vehicle.model,begin,end,modification:vehicle.modification});const r=await fetch('/api/fitment/'+stage+'?'+params,{signal:AbortSignal.timeout(65000)});if(!r.ok)throw new Error();const d=await r.json();if(serial!==vehicleRequest)return;if(stage==='makes')vehicle.makes=d.items;else if(stage==='models')vehicle.models=d.items;else if(stage==='years')vehicle.ranges=d.items;else if(stage==='modifications')vehicle.modifications=d.items;else{activeVehicle={ids:new Set(d.productIds),label:vehicle.make+' '+vehicle.model+' · '+vehicle.modification};filters=parseFilters('kind='+filters.kind);location.hash='catalog';}}catch{if(serial===vehicleRequest)vehicle.error='Не удалось загрузить варианты. Попробуйте ещё раз или обратитесь к менеджеру.';}finally{if(serial===vehicleRequest){vehicle.busy=false;render();if(stage==='products')$('.catalog-results')?.scrollIntoView({behavior:'smooth'});}}}
function openCar(){mode='car';render();$('#selector')?.scrollIntoView({behavior:'smooth',block:'center'});if(portal&&!vehicle.makes.length&&!vehicle.busy)vehicleFetch('makes');}
function render(){if(dialog.open)dialog.close();counts();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route()));if(route()==='cart')renderCart();else if(route()==='compare')renderCompare();else if(route()==='garage')renderGarage();else if(route()==='guide')renderGuide();else if(route()==='manager'){location.href='./manager/';return;}else renderCatalog(route()==='favorites');document.title=({cart:'Ваш комплект',compare:'Сравнение',garage:'Подбор по автомобилю',guide:'Помощь',favorites:'Избранное'}[route()]||'Шины и диски')+' — IMKONEX CARS';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const {action,id,value}=b.dataset;
if(action==='close-dialog')dialog.close();
if(action==='detail')renderDetail(id);
if(action==='add')add(id,Number(b.dataset.quantity)||1);
if(action==='favorite'){if(!byId.has(id))return;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save('favorites',favorites);render();}
if(action==='compare'){if(!byId.has(id))return;if(compare.includes(id))compare=compare.filter(x=>x!==id);else{if(compare.length>=4){toast('Можно сравнить до четырёх моделей');return;}if(compare.length&&byId.get(compare[0]).kind!==byId.get(id).kind){toast('Выберите товары одной категории');return;}compare.push(id);}save('compare',compare);render();}
if(action==='segment'||action==='category'){filters=parseFilters('kind='+b.dataset.kind);filters.category=b.dataset.category||'';sync();}
if(action==='mode'){mode=value;if(mode==='car')openCar();else render();}
if(action==='hero-car')openCar();
if(action==='vehicle-search')vehicleFetch('products');
if(action==='clear-vehicle'){activeVehicle=null;sync();}
if(action==='season'){filters.season=value;sync();}
if(action==='reset'){filters=parseFilters('kind='+filters.kind);activeVehicle=null;sync();}
if(action==='remove-filter'){filters[b.dataset.key]='';sync();}
if(action==='remove-brand'){filters.brands=filters.brands.filter(v=>v!==b.dataset.brand);sync();}
if(action==='page'){page=Number(b.dataset.page);render();$('.catalog-toolbar')?.scrollIntoView({behavior:'smooth'});}
if(action==='show-results')$('.catalog-results')?.scrollIntoView({behavior:'smooth'});
if(action==='open-filters')$('#filters')?.classList.add('open');
if(action==='close-filters')$('#filters')?.classList.remove('open');
if(action==='clear-cart'){cart=[];persistCart();render();}
if(action==='remove-cart'){cart=cart.filter(l=>l.id!==id);persistCart();render();}
if(action==='quantity'){const l=cart.find(l=>l.id===id);if(!l)return;const n=l.quantity+Number(b.dataset.delta);if(n<1||n>20||!effectiveOffer(byId.get(id),n)){toast('Проверьте доступное количество');return;}l.quantity=n;persistCart();render();}
if(action==='download-quote'){const t=cartTotals(cart,products);if(t.issues.length)return;const data={brand:'IMKONEX CARS',createdAt:new Date().toISOString(),total:t.total,lines:t.items.map(l=>({sku:l.product.sku,name:l.product.brand+' '+l.product.model,size:formatSize(l.product),quantity:l.quantity,price:l.offer.price})),notice:'Подбор для обсуждения с менеджером. Доставка рассчитывается отдельно.'};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='IMKONEX-podbor.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.filter){filters[el.dataset.filter]=el.type==='checkbox'?el.checked:el.value;const open=$('#filters')?.classList.contains('open');sync();if(open)$('#filters')?.classList.add('open');}if(el.dataset.brand){filters.brands=el.checked?[...new Set([...filters.brands,el.dataset.brand])]:filters.brands.filter(b=>b!==el.dataset.brand);sync();}if(el.dataset.vehicle){vehicleRequest++;vehicle.busy=false;activeVehicle=null;const k=el.dataset.vehicle;vehicle[k]=el.value;if(k==='make'){vehicle.model='';vehicle.years='';vehicle.modification='';vehicle.models=[];vehicle.ranges=[];vehicle.modifications=[];if(el.value)vehicleFetch('models');else render();}if(k==='model'){vehicle.years='';vehicle.modification='';vehicle.ranges=[];vehicle.modifications=[];if(el.value)vehicleFetch('years');else render();}if(k==='years'){vehicle.modification='';vehicle.modifications=[];if(el.value)vehicleFetch('modifications');else render();}if(k==='modification')render();}});
document.addEventListener('input',e=>{if(e.target.id==='brand-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('[data-brand-row]').forEach(el=>{el.hidden=!el.dataset.brandRow.includes(q);});}});
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();filters.q=new FormData(e.target).get('q').trim();sync();}});
document.addEventListener('error',e=>{const img=e.target;if(img.tagName==='IMG'&&!img.dataset.fallback){img.dataset.fallback='true';img.src=imageUrl('assets/product-unavailable.svg');img.alt='Изображение уточняется';}},true);
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
window.addEventListener('hashchange',()=>{if(['catalog','favorites'].includes(route())){filters=parseFilters(location.hash.split('?')[1]);page=1;}render();if(route()==='garage'&&portal&&!vehicle.makes.length&&!vehicle.busy)vehicleFetch('makes');window.scrollTo({top:0});});
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));render();if(route()==='garage'&&portal)vehicleFetch('makes');
