import {escapeHTML as h,money} from './domain.js';
import {wheelSpinner,withLoading} from './loading.js';
import {copyText} from './share.js';
export const statuses={new:'Заявка получена',confirmed:'Подтверждён менеджером',preparing:'Комплектуем',ready:'Готов к выдаче',shipped:'Передан в доставку',completed:'Получен',cancelled:'Отменён'};
let checkoutSession=null;
const errors={checkout_phone_mismatch:'Телефон заказа должен совпадать с подтверждённым номером в кабинете.',csrf_rejected:'Сессия изменилась. Закройте оформление и откройте его снова.',stock_or_price_unavailable:'Наличие или цена изменились. Вернитесь в каталог и обновите подбор.',checkout_quote_expired:'Проверка устарела. Откройте оформление заново.',checkout_price_changed:'Цена изменилась. Откройте оформление ещё раз и проверьте новую сумму.',too_many_requests:'Слишком много запросов. Повторите немного позже.',supplier_unavailable:'Не удалось проверить наличие. Попробуйте позже или позвоните менеджеру.',invalid_request:'Проверьте имя, телефон, город и согласие.',checkout_key_conflict:'Заявка уже обрабатывается. Используйте сохранённую ссылку на статус.'};
async function request(path,body){return withLoading(async()=>{const r=await fetch('/api/shop/'+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json',...(checkoutSession?.csrf?{'X-CSRF-Token':checkoutSession.csrf}:{})},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(90000)});const data=await r.json();if(!r.ok){const error=Error(errors[data.detail]||'Сервис временно недоступен. Попробуйте ещё раз.');error.status=r.status;throw error;}return data;});}
export async function startCheckout(lines,onSuccess){
 const dialog=document.querySelector('#dialog'),content=document.querySelector('#dialog-content');
 content.innerHTML=`<button class="icon-btn checkout-close" data-action="close-dialog" aria-label="Закрыть">×</button><h2 id="dialog-title">Проверяем ваш комплект</h2>${wheelSpinner('Уточняем цены и наличие')}`;dialog.showModal();
 try{
  checkoutSession=null;
  try{const r=await fetch('/api/customer/session',{credentials:'same-origin',signal:AbortSignal.timeout(5000)});if(r.ok)checkoutSession=await r.json();}catch{}
  const quote=await request('quote',{lines});if(!dialog.open)return;
  const key=crypto.randomUUID().replaceAll('-','');
  content.innerHTML=`<button class="icon-btn checkout-close" data-action="close-dialog" aria-label="Закрыть">×</button><span class="eyebrow">ВАШ СЛЕДУЮЩИЙ МАРШРУТ</span><h2 id="dialog-title">Оформление заказа</h2><div class="checkout-layout"><section class="checkout-lines">${quote.lines.map(l=>`<div><b>${h(l.name)}</b><span>Арт. ${h(l.sku)} · ${l.quantity} шт.</span><strong>${money(l.subtotal)}</strong></div>`).join('')}<p class="checkout-total">Товары <strong>${money(quote.total)}</strong></p><p class="form-hint">Доставка рассчитывается отдельно. Заявка не резервирует товар и не списывает деньги. Менеджер подтвердит итоговую сумму и наличие.</p></section><form id="checkout-form"><label class="field"><span>Ваше имя</span><input name="name" autocomplete="name" minlength="2" maxlength="100" required></label><label class="field"><span>Телефон</span><input name="phone" type="tel" autocomplete="tel" minlength="7" maxlength="40" required></label><label class="field"><span>Город</span><input name="city" autocomplete="address-level2" minlength="2" maxlength="150" required></label><label class="field"><span>Получение</span><select name="delivery"><option value="discuss">Обсудить с менеджером</option value="delivery">Хочу доставку</option><option value="pickup">Хочу самовывоз</option></select></label><label class="field"><span>Комментарий</span><textarea name="comment" maxlength="1000" rows="2" placeholder="Автомобиль, удобное время связи…"></textarea></label><label class="check-row checkout-consent"><input type="checkbox" name="consent" required><span>Даю <a href="/info/consent/#request" target="_blank" rel="noopener">согласие на обработку данных для заявки</a>. <a href="/info/privacy/" target="_blank" rel="noopener">Политика обработки данных</a></span></label><p class="form-hint">Продавец — ООО «ИНВЭКС». Отправляя заявку, вы просите менеджера согласовать заказ. <a href="/info/terms/" target="_blank" rel="noopener">Условия заказа</a> · <a href="/info/delivery/" target="_blank" rel="noopener">Доставка</a> · <a href="/info/returns/" target="_blank" rel="noopener">Возврат</a>.</p><p class="checkout-error" role="alert"></p><button class="btn btn-primary full">Отправить заявку</button></form></div>`;
  const form=content.querySelector('form');
  if(checkoutSession?.customer){form.elements.name.value=checkoutSession.customer.name||'';form.elements.phone.value=checkoutSession.customer.phone;form.elements.phone.readOnly=true;}
  let frozen=null,submitting=false;
  form.addEventListener('submit',async e=>{e.preventDefault();if(submitting||!form.reportValidity())return;const button=form.querySelector('button');submitting=true;button.disabled=true;button.innerHTML=wheelSpinner('Отправляем');
   // Reuse identical request after a network timeout: a double click/retry never duplicates it.
   frozen ||= {...Object.fromEntries(new FormData(form)),quoteId:quote.quoteId,key,consent:true,consentVersion:'2026-09-24'};
   try{const result=await request('orders',frozen);const url=new URL('/order/#'+result.token,location.origin).href;
    try{localStorage.setItem('imkonex-last-order',JSON.stringify({id:result.id,url}));}catch{}
    onSuccess();content.innerHTML=`<div class="checkout-success"><span class="eyebrow">ЗАЯВКА ПОЛУЧЕНА</span><h2 id="dialog-title">Спасибо за ваш выбор.</h2><p>Заказ <strong>${h(result.id)}</strong></p><p>Менеджер проверит комплект и свяжется с вами. Сохраните ссылку: по ней можно следить за статусом.</p><a class="btn btn-primary" href="${h(url)}">Статус заказа →</a><button class="btn btn-ghost" id="copy-order-link">Скопировать ссылку</button><p id="copy-order-note" role="status"></p></div>`;
    content.querySelector('#copy-order-link').onclick=async()=>{try{await copyText(url);content.querySelector('#copy-order-note').textContent='Ссылка скопирована';}catch{content.querySelector('#copy-order-note').textContent=url;}};
   }catch(error){if(error.status===422)frozen=null;form.querySelector('.checkout-error').textContent=error.message;button.textContent='Повторить отправку';button.disabled=false;}finally{submitting=false;}
  });
 }catch(error){content.innerHTML=`<h2 id="dialog-title">Проверьте комплект</h2><p>${h(error.message)}</p><button class="btn btn-primary" data-action="close-dialog">Вернуться</button>`;}
}
export async function renderShopPage(route,main){
 if(['delivery','payment','returns','contacts'].includes(route)){location.replace('/info/'+route+'/');return;}

 const titles={delivery:'Доставка',payment:'Оплата',returns:'Возврат и обмен',contacts:'Связаться с нами','order-status':'Статус заказа'};
 const marker=Symbol();main._shopRoute=marker;
 main.innerHTML=`<div class="breadcrumb"><a href="#catalog">Каталог</a><span>/</span>${titles[route]}</div><section class="shop-info"><span class="eyebrow">ПОКУПАТЕЛЯМ</span><h1>${titles[route]}</h1><div id="shop-page-content">${wheelSpinner('Загружаем')}</div></section>`;
 if(route==='order-status'){
  let saved=null;try{saved=JSON.parse(localStorage.getItem('imkonex-last-order'));}catch{}
  const area=main.querySelector('#shop-page-content');area.innerHTML=`<p>Откройте персональную ссылку, которую вы получили после оформления заявки.</p>${saved&&/^https?:\/\//.test(saved.url)?`<a class="btn btn-primary" id="last-order">Мой последний заказ · ${h(saved.id)}</a>`:''}<form id="track-order"><label class="field"><span>Ссылка или код отслеживания</span><input name="token" required autocomplete="off" placeholder="Вставьте ссылку на заказ"></label><button class="btn btn-primary">Посмотреть статус</button><p role="alert"></p></form>`;
  if(area.querySelector('#last-order')){try{const u=new URL(saved.url);if(u.origin===location.origin&&/^#[\w-]{43}$/.test(u.hash))area.querySelector('#last-order').href=u.href;}catch{}}
  area.querySelector('form').onsubmit=e=>{e.preventDefault();const value=new FormData(e.target).get('token').trim();let token=value;try{if(value.includes('://'))token=new URL(value).hash.slice(1);}catch{}if(!/^[\w-]{43}$/.test(token)){e.target.querySelector('p').textContent='Нужна персональная ссылка или код из неё.';return;}location.href='/order/#'+token;};return;
 }
 try{const settings=await request('settings');if(main._shopRoute!==marker||location.hash.slice(1).split('?')[0]!==route)return;const content=main.querySelector('#shop-page-content');if(!content)return;
  content.innerHTML=route==='contacts'?`<div class="shop-contact"><a href="tel:${h(settings.contactPhone.replace(/[^+\d]/g,''))}">${h(settings.contactPhone)}</a><a href="mailto:${h(settings.contactEmail)}">${h(settings.contactEmail)}</a><p>${h(settings.pickupAddress)}</p></div>`:`<p class="policy-text">${h(settings[route])}</p>${route==='delivery'?`<div class="info-callout"><strong>Самовывоз</strong><p>${h(settings.pickupAddress)}</p></div>`:''}<a class="btn btn-primary" href="tel:${h(settings.contactPhone.replace(/[^+\d]/g,''))}">Уточнить условия ↗</a>`;
 }catch(error){if(main._shopRoute===marker&&main.querySelector('#shop-page-content'))main.querySelector('#shop-page-content').innerHTML=`<p>${h(error.message)}</p><a href="tel:88003013688">8 800 301-36-88</a>`;}
}
export async function renderOrder(main){const token=location.hash.slice(1);main.innerHTML=wheelSpinner('Загружаем заказ');if(!/^[\w-]{43}$/.test(token)){main.innerHTML='<h1>Нужна ссылка на заказ</h1><p>Откройте персональную ссылку после оформления.</p>';return;}
 try{const order=await request('orders/'+token);main.innerHTML=`<span class="eyebrow">ВАШ ЗАКАЗ</span><h1>${h(order.id)}</h1><div class="order-state">${h(statuses[order.status])}</div><ol class="order-timeline">${order.history.map(e=>`<li><strong>${h(statuses[e.status])}</strong><time>${new Date(e.at*1000).toLocaleString('ru-RU')}</time>${e.note?`<p>${h(e.note)}</p>`:''}</li>`).join('')}</ol><div class="status-lines">${order.lines.map(l=>`<div><strong>${h(l.name)}</strong><span>Арт. ${h(l.sku)} · ${l.quantity} шт.</span><b>${money(l.subtotal)}</b></div>`).join('')}</div><p class="checkout-total">Товары <strong>${money(order.total)}</strong></p><p>Доставка и условия оплаты согласуются с менеджером.</p><button class="btn btn-primary" id="refresh-status">Обновить статус</button><a class="btn btn-ghost" href="tel:88003013688">Связаться с менеджером</a>`;main.querySelector('#refresh-status').onclick=()=>renderOrder(main);
 }catch{main.innerHTML='<h1>Не удалось открыть заказ</h1><p>Проверьте ссылку или попробуйте ещё раз.</p><button id="retry-status" class="btn btn-primary">Повторить</button>';main.querySelector('button').onclick=()=>renderOrder(main);}}
