import {escapeHTML as h,money} from '../domain.js';
import {statuses} from '../shop.js';
import {copyText} from '../share.js';
const transitions={new:['confirmed','cancelled'],confirmed:['preparing','cancelled'],preparing:['ready','shipped','cancelled'],ready:['shipped','completed','cancelled'],shipped:['completed'],completed:[],cancelled:[]};
let ctx,pricing,customers=[],activeCustomer=null,policyDraft=null;
const modeNames={supplier:'Розница 4точки',discount:'Скидка от розницы 4точки',markup:'Наценка к закупке'};
export function setupManagement(context){ctx=context;}
export function clearManagement(){pricing=null;customers=[];activeCustomer=null;policyDraft=null;}
export async function showManagement(tab){
 if(tab==='pricing')return renderPricing();
 if(tab==='customers')return renderCustomers();
 if(tab==='settings')return renderSettings();
}
async function renderPricing(){pricing=await ctx.api('pricing');if(ctx.activeTab()!=='pricing')return;ctx.shell(ctx.title('АВТОМАТИЧЕСКИЕ ЦЕНЫ','Правила по категориям')+`<section class="manager-panel"><p>Все цены защищены минимумом <strong>закупка + 100 ₽ за штуку</strong>. Если заданная скидка или розница ниже этого уровня, применяется минимальная цена. Доход указан до доставки, налогов и других расходов.</p><p class="manager-note">Скидка поставщика = 1 − сумма закупочных цен / сумма розничных цен по проверенным предложениям складов. Это взвешенный показатель доступной выборки, а не единая договорная скидка. У каждой позиции цена рассчитывается отдельно.</p><div class="manager-table-wrap"><table class="manager-data-table pricing-rules"><thead><tr><th>Категория</th><th>Проверено предложений</th><th>Скидка поставщика</th><th>Наше правило</th><th></th></tr></thead><tbody>${pricing.groups.map(g=>`<tr><td><strong>${h(g.label)}</strong><small>${g.products} товаров</small></td><td>${g.checkedOffers}</td><td>${g.supplierDiscount==null?'Нет закупки':g.supplierDiscount+'%'}</td><td>${g.rule?h(modeNames[g.rule.mode])+(['discount','markup'].includes(g.rule.mode)?' · '+g.rule.percent+'%':''):'Наследуется'}<small>Доход от ${Math.max(100,g.rule?.minimum||100)} ₽</small></td><td><button class="table-action" data-admin-action="edit-policy" data-key="${g.category}">Настроить</button></td></tr>`).join('')}</tbody></table></div><p class="manager-note">Приоритет: правило склада → товара → раздела шин → категории → общее. Минимум 100 ₽ действует при любом правиле. Без актуальной закупки цена не публикуется.</p><p>Обновление закупки: ${h(({running:'загружаем',ready:'завершено',paused:'продолжится автоматически',unavailable:'API недоступен'}[pricing.sync.status]||'ожидает запуска'))}${pricing.sync.total?' · '+pricing.sync.done+' / '+pricing.sync.total:''}</p><button class="btn" data-admin-action="reload-pricing">Обновить состояние</button></section>`);}
function editPolicy(key){const g=pricing.groups.find(g=>g.category===key);if(!g)return;policyDraft=null;const r=g.rule||{mode:'supplier',percent:0,minimum:100,roundTo:.01};ctx.show('Цены · '+g.label,`<form id="category-policy-form" data-key="${h(key)}"><label class="field"><span>Способ расчёта</span><select name="mode">${Object.entries(modeNames).map(([v,l])=>`<option value="${v}" ${r.mode===v?'selected':''}>${l}</option>`).join('')}</select></label><div class="manager-form-grid"><label class="field"><span>Скидка / наценка, %</span><input name="percent" type="number" min="0" max="1000" step=".01" value="${r.percent||0}"></label><label class="field"><span>Минимальный доход, ₽ / шт.</span><input name="minimum" type="number" min="100" max="1000000" step=".01" value="${Math.max(100,r.minimum||100)}"></label><label class="field"><span>Округление</span><select name="roundTo"><option value="0.01" ${r.roundTo===.01?'selected':''}>До копейки</option><option value="10" ${r.roundTo===10?'selected':''}>Вверх до 10 ₽</option></select></label></div><p class="manager-note">Сначала проверим, как изменятся цены. Индивидуальные правила сохраняют приоритет.</p><button class="btn btn-primary">Рассчитать изменения</button><button type="button" class="btn" data-admin-action="inherit-policy" data-key="${h(key)}">Наследовать общее правило</button><p class="manager-error" role="alert"></p><div id="policy-preview"></div></form>`);}
async function renderCustomers(){customers=(await ctx.api('customer-orders')).items;if(ctx.activeTab()!=='customers')return;ctx.shell(ctx.title('ОБРАЩЕНИЯ С ВИТРИНЫ','Заказы покупателей')+`<section class="manager-panel"><div class="manager-search"><input id="customer-search" placeholder="Номер, имя, телефон, артикул" aria-label="Найти заказ"><select id="customer-status-filter"><option value="">Все статусы</option>${Object.entries(statuses).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><button class="btn" data-admin-action="reload-customers">Обновить</button></div><p class="manager-note">Покупатель оставляет заявку. Отправка заказа поставщику выполняется отдельно после проверки менеджером. Здесь показаны последние 200 заявок.</p><div id="customer-list"></div></section>`);renderCustomerRows();}
function renderCustomerRows(){const q=document.querySelector('#customer-search').value.trim().toLowerCase(),state=document.querySelector('#customer-status-filter').value;const rows=customers.filter(o=>(!state||o.status===state)&&JSON.stringify([o.id,o.customer,...o.lines.map(l=>l.sku)]).toLowerCase().includes(q));document.querySelector('#customer-list').innerHTML=`<div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Состав</th><th>Сумма товаров</th><th>Статус</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${h(o.id)}</b><small>${ctx.date(o.createdAt)}</small></td><td>${h(o.customer.name)}<small>${h(o.customer.phone)} · ${h(o.customer.city)}</small></td><td>${o.lines.length} поз. · ${o.lines.reduce((s,l)=>s+l.quantity,0)} шт.</td><td>${money(o.total)}</td><td>${h(statuses[o.status])}</td><td><button class="table-action" data-admin-action="customer" data-id="${h(o.id)}">Открыть →</button></td></tr>`).join('')||'<tr><td colspan="6">Заявок пока нет.</td></tr>'}</tbody></table></div>`;}
function openCustomer(id){const o=customers.find(o=>o.id===id);if(!o)return;activeCustomer=o;const d=o.customer;ctx.show('Заказ '+o.id,`<div class="customer-details"><p><strong>${h(d.name)}</strong> · ${h(d.phone)} · ${h(d.city)}</p><p>Получение: ${h({delivery:'запрошена доставка',pickup:'запрошен самовывоз',discuss:'обсудить с клиентом'}[d.delivery])}</p><p>${h(d.comment)}</p></div><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Артикул / товар</th><th>Склад</th><th>Количество</th><th>Продажа</th></tr></thead><tbody>${o.lines.map(l=>`<tr><td>${h(l.sku)}<small>${h(l.name)}</small></td><td>${h(l.warehouse)}</td><td>${l.quantity}</td><td>${money(l.subtotal)}</td></tr>`).join('')}</tbody></table></div><p><strong>Сумма товаров ${money(o.total)}</strong></p><div class="share-actions"><button class="btn" data-admin-action="customer-link">Ссылка для клиента</button>${!['completed','cancelled'].includes(o.status)?'<button class="btn btn-primary" data-admin-action="customer-procure">Подготовить закупку</button>':''}</div><h3>История</h3><div class="customer-history">${o.history.map(e=>`<p>${ctx.date(e.at)} · <strong>${h(statuses[e.status])}</strong>${e.note?'<br>'+h(e.note):''}</p>`).join('')}</div>${transitions[o.status].length?`<form id="customer-status-form"><label class="field"><span>Следующий статус</span><select name="status">${transitions[o.status].map(v=>`<option value="${v}">${h(statuses[v])}</option>`).join('')}</select></label><label class="field"><span>Сообщение покупателю (видно по ссылке)</span><textarea name="note" rows="2" maxlength="1000" placeholder="Например: готово к выдаче после согласования времени"></textarea></label><p class="manager-error" role="alert"></p><button class="btn btn-primary">Обновить статус</button></form>`:''}`);}
async function renderSettings(){const r=await fetch('/api/shop/settings'),s=await r.json();if(ctx.activeTab()!=='settings')return;ctx.shell(ctx.title('УСЛОВИЯ ПОКУПКИ','Страницы магазина')+`<section class="manager-panel"><p>Укажите действующие условия вашего магазина. Изменения появятся на витрине после сохранения.</p><form id="shop-settings-form">${[['delivery','Доставка'],['payment','Оплата'],['returns','Возврат и обмен'],['pickupAddress','Адрес / условия самовывоза'],['contactPhone','Телефон'],['contactEmail','Email']].map(([k,l])=>`<label class="field"><span>${l}</span>${['delivery','payment','returns'].includes(k)?`<textarea name="${k}" rows="4" maxlength="5000" minlength="20" required>${h(s[k])}</textarea>`:`<input name="${k}" value="${h(s[k])}" maxlength="${k==='pickupAddress'?500:150}" required>`}</label>`).join('')}<p class="manager-note">Текст страницы оплаты не подключает эквайринг. Для приёма денег потребуется отдельное подключение платёжного сервиса и кассы.</p><p class="manager-error" role="alert"></p><button class="btn btn-primary">Сохранить условия</button></form></section>`);}
document.addEventListener('input',e=>{if(e.target.id==='customer-search')renderCustomerRows();if(e.target.closest('#category-policy-form')){policyDraft=null;document.querySelector('#policy-preview').replaceChildren();}});
document.addEventListener('change',e=>{if(e.target.id==='customer-status-filter')renderCustomerRows();if(e.target.closest('#category-policy-form')){policyDraft=null;document.querySelector('#policy-preview').replaceChildren();}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-admin-action]');if(!b||b.disabled)return;const a=b.dataset.adminAction;b.disabled=true;try{
 if(a==='edit-policy')editPolicy(b.dataset.key);
 if(a==='reload-pricing')await renderPricing();
 if(a==='inherit-policy'){await ctx.api('pricing/'+b.dataset.key,'DELETE');ctx.close();await renderPricing();}
 if(a==='apply-policy'&&policyDraft){await ctx.api('pricing/'+policyDraft.key,'PUT',policyDraft.rule);ctx.close();await renderPricing();ctx.toast('Правило сохранено. Минимум дохода защищён.');}
 if(a==='reload-customers')await renderCustomers();
 if(a==='customer')openCustomer(b.dataset.id);
 if(a==='customer-link'&&activeCustomer){await copyText(new URL('/order/#'+activeCustomer.token,location.origin).href);ctx.toast('Ссылка скопирована');}
 if(a==='customer-procure'&&activeCustomer){await ctx.procure(activeCustomer);}
 }catch(error){ctx.toast(error.message);}finally{b.disabled=false;}});
document.addEventListener('submit',async e=>{if(!['category-policy-form','customer-status-form','shop-settings-form'].includes(e.target.id))return;e.preventDefault();const f=e.target,b=f.querySelector('button:not([type]),button[type="submit"]');if(b.disabled)return;b.disabled=true;const d=Object.fromEntries(new FormData(f));try{
 if(f.id==='category-policy-form'){const rule={mode:d.mode,percent:Number(d.percent),minimum:Number(d.minimum),roundTo:Number(d.roundTo)};if(rule.mode==='discount'&&rule.percent>100)throw Error('Скидка не может превышать 100%.');const result=await ctx.api('pricing/'+f.dataset.key+'/preview','POST',rule);policyDraft={key:f.dataset.key,rule};f.querySelector('#policy-preview').innerHTML=`<div class="policy-impact"><p><b>${result.affected}</b> предложений изменятся · <b>${result.floorApplied}</b> защищены минимумом · ${result.unknown} без актуальной закупки · ${result.overridden} сохранят индивидуальные или более точные правила.</p><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Артикул / склад</th><th>Закупка</th><th>Розница</th><th>Продажа</th><th>Доход / шт.</th></tr></thead><tbody>${result.examples.map(r=>`<tr><td>${h(r.sku)}<small>${h(r.warehouse)}</small></td><td>${money(r.purchase)}</td><td>${money(r.retail)}</td><td>${money(r.sale)}${r.floorApplied?'<small>Минимум дохода</small>':''}</td><td>${money(r.gain)}</td></tr>`).join('')}</tbody></table></div><button type="button" class="btn btn-primary" data-admin-action="apply-policy">Применить правило</button></div>`;}
 if(f.id==='customer-status-form'&&activeCustomer){const id=activeCustomer.id;await ctx.api('customer-orders/'+id+'/status','PUT',{...d,updatedAt:activeCustomer.updatedAt});ctx.close();await renderCustomers();openCustomer(id);}
 if(f.id==='shop-settings-form'){await ctx.api('shop-settings','PUT',d);ctx.toast('Условия магазина сохранены');}
 }catch(error){f.querySelector('.manager-error').textContent=error.message;}finally{b.disabled=false;}});
