import {escapeHTML as h,money,formatSize} from '../domain.js';
const root=document.querySelector('#manager-app'),dialog=document.querySelector('#manager-dialog'),body=document.querySelector('#manager-dialog-content');
let csrf='',tab='overview',status={},items=[],orders=[],q='',page=1,total=0,cart=[],preview=null,activeOrder=null,busy=false,toastTimer;
const states={draft:'Предпросмотр',submitting:'Отправка · требуется сверка',submitted:'Создан у поставщика',changed:'Цена или остаток изменились',rejected:'Отклонён',unknown:'Результат требует сверки',check_failed:'Не удалось проверить остатки'};
const messages={invalid_login:'Проверьте логин и пароль.',manager_password_not_configured:'Пароль кабинета ещё не настроен на сервере.',supplier_not_configured:'Добавьте доступ к API в настройках сервера.',supplier_unavailable:'Поставщик временно не отвечает. Повторите чтение позже.',supplier_schema_unavailable:'Не удалось загрузить схему API. Проверьте соединение сервера с поставщиком.',supplier_schema_changed:'Формат API изменился. Отправка остановлена до проверки.',supplier_rejected:'Поставщик отклонил запрос.',purchase_price_unavailable:'Для этой позиции пока нет подтверждённой закупочной цены.',insufficient_supplier_stock:'На выбранном складе недостаточно товара.',purchase_changed_review_again:'Цена закупки или остаток изменились. Сформируйте новый предпросмотр.',preview_expired:'Предпросмотр устарел. Проверьте заказ ещё раз.',order_result_unknown:'Ответ о создании заказа не получен. Не отправляйте заказ повторно: сначала проверьте его в кабинете поставщика.',supplier_orders_disabled:'Отправка заказов ещё не включена в настройках сервера.',order_already_processed:'Этот заказ уже обработан. Повторная отправка заблокирована.',origin_rejected:'Адрес сайта не совпадает с PUBLIC_ORIGIN на сервере.',csrf_rejected:'Сессия устарела. Войдите снова.',too_many_requests:'Слишком много запросов. Подождите немного.',invalid_request:'Проверьте заполнение полей.'};
const date=t=>t?new Date(typeof t==='number'?t*1000:t).toLocaleString('ru-RU'):'—';
function toast(s){const n=document.querySelector('#manager-toast');n.textContent=s;n.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('visible'),6000);}
async function api(path,method='GET',payload){const r=await fetch('/api/manager/'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(payload?{body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(90000)});let data;try{data=await r.json();}catch{throw new Error('Для кабинета нужен Web Service. Откройте адрес серверной версии каталога.');}if(!r.ok){if(r.status===401&&path!=='login'){csrf='';login();}throw new Error((messages[data.detail]||'Не удалось выполнить действие.')+(data.providerCode?' Код поставщика: '+data.providerCode:''));}return data;}
function login(error=''){root.innerHTML=`<main class="login-layout"><section class="login-brand"><a href="../"><img src="../assets/imkonex-cars.svg" width="260" alt="IMKONEX CARS"></a><span class="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</span><h1>Ваш каталог.<br>Ваши решения.</h1><p>Цены, закупка и заказы —<br>в одном кабинете.</p><a class="login-back" href="../">← Вернуться в каталог</a></section><section class="login-panel"><form id="login-form"><span class="eyebrow">ДЛЯ СОТРУДНИКОВ</span><h2>Вход в кабинет</h2><p>Используйте доступ менеджера IMKONEX.</p><label class="field"><span>Логин</span><input name="login" autocomplete="username" required value="manager"></label><label class="field"><span>Пароль</span><input name="password" type="password" autocomplete="current-password" required></label><p class="manager-error" role="alert">${h(error)}</p><button class="btn btn-primary full">Войти</button><small>Доступ к закупочным ценам и заказам защищён.</small></form></section></main>`;}
function shell(content){root.innerHTML=`<div class="manager-shell"><aside class="manager-rail"><a href="../" class="manager-logo">IMKONEX<span>CARS / MANAGER</span></a><nav>${[['overview','01','Обзор'],['products','02','Цены и закупка'],['order','03','Новый заказ'],['orders','04','Заказы и статусы']].map(([id,n,title])=>`<button data-action="tab" data-tab="${id}" class="${tab===id?'active':''}"><span>${n}</span>${title}</button>`).join('')}</nav><div class="rail-bottom"><a href="../" target="_blank" rel="noopener">Открыть витрину ↗</a><button data-action="logout">Выйти из кабинета</button></div></aside><main class="manager-workspace"><header class="manager-top"><span>Рабочее пространство</span><span>IMKONEX CARS <i></i></span></header>${content}</main></div>`;}
const title=(small,large)=>`<div class="manager-title"><span class="eyebrow">${small}</span><h1>${large}</h1></div>`;
function renderOverview(){shell(title('ВСЁ ПОД КОНТРОЛЕМ','Обзор каталога')+`<div class="manager-metrics"><article><span>Товары в каталоге</span><strong>${status.products||0}</strong><small>Публичная витрина</small></article><article><span>Индивидуальные цены</span><strong>${status.rules||0}</strong><small>Сохранённые правила</small></article><article><span>Заказы</span><strong>${status.orders||0}</strong><small>Предпросмотры и отправленные</small></article></div><div class="manager-panels"><section class="manager-panel"><span class="eyebrow">ДАННЫЕ И ПОДКЛЮЧЕНИЕ</span><h2>Состояние системы</h2><dl><dt>Последняя выгрузка каталога</dt><dd>${h(date(status.updatedAt))}</dd><dt>API «4точки»</dt><dd>${status.supplierConfigured?'Доступ настроен':'Требуется настройка доступа'}</dd><dt>Отправка заказов</dt><dd>${status.ordersEnabled?'Включена':'Выключена в настройках сервера'}</dd></dl><p class="manager-note">Цена закупки загружается по запросу. Перед отправкой заказа наличие и цена проверяются повторно.</p><button class="btn btn-ghost" data-action="reload">Обновить состояние</button></section><section class="manager-panel dark"><span class="eyebrow">ЦЕНООБРАЗОВАНИЕ</span><h2>Контролируйте<br>цену и прибыль.</h2><p>Установите свою цену или наценку к закупке. Изменения сохраняются на сервере и применяются в серверной витрине.</p><button class="btn btn-lime" data-action="tab" data-tab="products">Перейти к товарам →</button></section></div>`);}
function productRow(p){const costs=p.offers.map(o=>o.purchasePrice).filter(v=>v!==null);const sales=p.offers.map(o=>o.salePrice).filter(v=>v!==null);const mode={supplier:'Базовая цена',fixed:'Своя цена',markup:'Наценка к закупке'}[p.priceRule.mode];return `<tr><td><span class="table-brand">${h(p.brand)}</span><strong>${h(p.model)}</strong><small>${h(formatSize(p))}</small><small>${h(p.sku)}</small></td><td>${costs.length?'<strong>'+money(Math.min(...costs))+'</strong>':'<span class="muted">Не запрошена</span>'}</td><td>${sales.length?'<strong>'+money(Math.min(...sales))+'</strong>':'По запросу'}<small>${mode}</small></td><td><button class="table-action" data-action="edit-price" data-id="${p.id}">Настроить цену</button><button class="table-action" data-action="add-order" data-id="${p.id}">В заказ →</button></td></tr>`;}
function renderProducts(){shell(title('ПРИБЫЛЬ В ДЕТАЛЯХ','Цены и закупка')+`<section class="manager-panel"><form id="product-search" class="manager-search"><input name="q" type="search" value="${h(q)}" placeholder="Артикул, бренд или модель" aria-label="Поиск товара"><button class="btn btn-primary">Найти</button><button type="button" class="btn" data-action="refresh-costs" ${items.length?'':'disabled'}>Обновить закупку</button></form><p class="manager-note">Закупочная цена видна только в кабинете. Кнопка обновляет товары на текущей странице.</p><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Товар</th><th>Закупка, от</th><th>Продажа, от</th><th>Действия</th></tr></thead><tbody>${items.map(productRow).join('')||'<tr><td colspan="4">По вашему запросу ничего не найдено.</td></tr>'}</tbody></table></div><div class="manager-paging"><button class="btn" data-action="prev-products" ${page===1?'disabled':''}>← Назад</button><span>Страница ${page} · товаров ${total}</span><button class="btn" data-action="next-products" ${page*20>=total?'disabled':''}>Далее →</button></div></section>`);}
function show(title,html){body.innerHTML=`<div class="dialog-header"><h2>${h(title)}</h2><button class="icon-btn" data-action="close-dialog" aria-label="Закрыть">×</button></div><div class="dialog-body">${html}</div>`;dialog.showModal();}
function editPrice(id){const p=items.find(p=>p.id===id);if(!p)return;const rule=p.priceRule;show('Цена · '+p.sku,`<h3>${h(p.brand+' '+p.model)}</h3><form id="price-form" data-id="${id}"><label class="field"><span>Правило продажи</span><select name="mode">${[['supplier','Базовая розничная цена'],['fixed','Моя фиксированная цена'],['markup','Наценка к закупочной цене']].map(([v,l])=>`<option value="${v}" ${v===rule.mode?'selected':''}>${l}</option>`).join('')}</select></label><div class="manager-form-grid"><label class="field"><span>Фиксированная цена, ₽</span><input name="price" type="number" min="0.01" max="100000000" step="0.01" value="${rule.price||''}"></label><label class="field"><span>Наценка, %</span><input name="percent" type="number" min="0" max="1000" step="0.01" value="${rule.percent||0}"></label><label class="field"><span>Минимальная наценка, ₽</span><input name="minimum" type="number" min="0" max="1000000" step="0.01" value="${rule.minimum||0}"></label></div><p class="manager-note">Наценка считается отдельно по закупке каждого склада и округляется вверх до 10 ₽. Закупка обновляется автоматически раз в 6 часов. Если она не обновлялась больше суток, предложение с этим правилом скрывается до обновления.</p><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Склад</th><th>Закупка</th><th>Продажа</th><th>Прибыль / шт.</th></tr></thead><tbody>${p.offers.map(o=>`<tr><td>${h(o.warehouse)}<small>${h(date(o.purchaseCheckedAt))}</small></td><td>${o.purchasePrice===null?'—':money(o.purchasePrice)}</td><td>${o.salePrice===null?'—':money(o.salePrice)}</td><td class="${o.profit!==null&&o.profit<0?'loss':''}">${o.profit===null?'—':money(o.profit)}</td></tr>`).join('')}</tbody></table></div><p id="price-error" class="manager-error" role="alert"></p><button class="btn btn-primary">Сохранить цену</button></form>`);}
function addOrder(id){const p=items.find(p=>p.id===id);if(!p)return;show('Добавить в заказ',`<h3>${h(p.brand+' '+p.model)}</h3><p class="manager-note">${h(p.sku)} · ${h(formatSize(p))}</p><form id="add-order-form" data-id="${id}"><label class="field"><span>Склад</span><select name="warehouseId">${p.offers.map(o=>`<option value="${o.warehouseId}">${h(o.warehouse)} · ${o.liveStock??o.stock} шт.${o.purchasePrice!==null?' · закупка '+money(o.purchasePrice):''}</option>`).join('')}</select></label><label class="field"><span>Количество</span><input name="quantity" type="number" min="1" max="1000" value="4" required></label><button class="btn btn-primary">Добавить</button></form>`);}
function renderNewOrder(){shell(title('ОТ ПОДБОРА К РЕЗЕРВУ','Новый заказ')+`<section class="manager-panel">${cart.length?`<div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Товар</th><th>Склад</th><th>Количество</th><th></th></tr></thead><tbody>${cart.map((l,i)=>`<tr><td><strong>${h(l.name)}</strong><small>${h(l.sku)}</small></td><td>${h(l.warehouse)}</td><td>${l.quantity}</td><td><button class="table-action" data-action="remove-line" data-index="${i}">Удалить</button></td></tr>`).join('')}</tbody></table></div><form id="preview-order-form"><div class="manager-form-grid"><label class="field"><span>Клиент (для себя)</span><input name="clientName" maxlength="150"></label><label class="field"><span>Телефон клиента (для себя)</span><input name="clientPhone" maxlength="80"></label><label class="field"><span>ID покупателя у поставщика, если нужен</span><input name="customerId" type="number" min="1"></label></div><label class="check-row"><input name="test" type="checkbox" checked><span>Тестовый заказ в статусе «я формирую»</span></label><p class="manager-note">Снимите флажок для боевого заказа с резервированием. После проверки вы ещё раз увидите сумму и подтвердите отправку. Доставка оформляется отдельно.</p><p id="order-error" class="manager-error" role="alert"></p><button class="btn btn-primary">Проверить цены и остатки →</button></form>`:`<div class="manager-empty"><h2>Начните с товаров</h2><p>Найдите артикул в разделе «Цены и закупка» и добавьте его в заказ с нужного склада.</p><button class="btn btn-primary" data-action="tab" data-tab="products">Выбрать товары →</button></div>`}</section>`);}
function previewOrder(){show('Подтверждение заказа',`<div class="order-review ${preview.test?'test-order':''}"><span class="eyebrow">${preview.test?'ТЕСТОВЫЙ ЗАКАЗ':'БОЕВОЙ ЗАКАЗ · РЕЗЕРВ ТОВАРА'}</span><h2>${money(preview.purchaseTotal)}</h2><p>Сумма закупки без доставки</p><dl><dt>Продажа клиенту</dt><dd>${money(preview.saleTotal)}</dd><dt>Разница до расходов</dt><dd>${money(preview.saleTotal-preview.purchaseTotal)}</dd></dl><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Товар / склад</th><th>Шт.</th><th>Закупка / шт.</th></tr></thead><tbody>${preview.lines.map(l=>`<tr><td>${h(l.name)}<small>${h(l.warehouse)}</small></td><td>${l.quantity}</td><td>${money(l.purchasePrice)}</td></tr>`).join('')}</tbody></table></div><p class="manager-note">Предпросмотр действителен 2 минуты. ${preview.test?'Тестовый заказ создаётся у поставщика в статусе «я формирую».':'Нажатие кнопки отправит заказ поставщику для резервирования товара.'}</p><p id="submit-error" class="manager-error" role="alert"></p><button class="btn btn-primary full" data-action="submit-order">${preview.test?'Создать тестовый заказ':'Подтвердить и отправить заказ'}</button></div>`);}
function renderOrders(){shell(title('ПРОЗРАЧНЫЙ ПРОЦЕСС','Заказы и исполнение')+`<section class="manager-panel"><div class="manager-section-top"><p>Откройте заказ, чтобы проверить статус поставщика.</p><button class="btn" data-action="reload-orders">Обновить список</button></div><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Закупка</th><th>Состояние</th><th></th></tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${h(o.providerNumber||o.id)}</strong><small>${h(date(o.createdAt))}${o.test?' · тестовый':''}</small></td><td>${h(o.clientName||'—')}</td><td>${money(o.purchaseTotal)}</td><td><span class="order-badge ${['unknown','submitting'].includes(o.status)?'attention':''}">${h(o.providerStatus?.statusName||states[o.status]||o.status)}</span></td><td><button class="table-action" data-action="open-order" data-id="${o.id}">Открыть →</button></td></tr>`).join('')||'<tr><td colspan="5">Заказов пока нет.</td></tr>'}</tbody></table></div></section>`);}
function orderDetail(o){activeOrder=o.id;const s=o.providerStatus||{};show('Заказ '+(o.providerNumber||o.id),`<div class="order-detail"><span class="order-badge">${h(s.statusName||states[o.status])}</span><p class="manager-note">${h(o.id)}${o.test?' · Тестовый':''}</p><h2>${money(o.purchaseTotal)}</h2><p class="manager-note">Закупка без доставки. Продажа: ${money(o.saleTotal)}</p><dl><dt>Клиент</dt><dd>${h(o.clientName||'—')} ${h(o.clientPhone||'')}</dd><dt>Оплата</dt><dd>${h(s.paymentPercent||'—')}${s.paymentPercent?'%':''}</dd><dt>Отгрузка</dt><dd>${h(s.shipmentType||'—')} ${h(s.shipmentDate||'')}</dd><dt>Пункт выдачи</dt><dd>${h(s.pickupWarehouseName||'—')} ${h(s.pickupWarehouseAddress||'')}</dd><dt>Доставка</dt><dd>${h(s.deliveryAddress||'—')}</dd><dt>Интервал доставки</dt><dd>${h(s.deliveryIntervalStart||'—')} — ${h(s.deliveryIntervalEnd||'—')}</dd><dt>Проверено</dt><dd>${h(date(o.statusCheckedAt))}</dd></dl>${o.history?.length?`<ol class="order-history">${o.history.map(e=>`<li><strong>${h(e.name)}</strong><small>${h(date(e.at))}</small></li>`).join('')}</ol>`:''}${o.providerReviewRequired?'<div class="manager-alert">Поставщик вернул номер заказа с замечанием. Проверьте состав и исполнение у поставщика перед продолжением.</div>':''}${o.providerId?`<button class="btn btn-primary" data-action="refresh-order" data-id="${o.id}">Обновить статус</button><label class="check-row"><input id="auto-status" type="checkbox" checked><span>Обновлять раз в минуту, пока открыт заказ</span></label>`:''}${['unknown','submitting'].includes(o.status)?`<div class="manager-alert"><h3>Проверьте заказ у поставщика</h3><p>Отправка могла завершиться успешно. Повторный запрос заблокирован. Сверьте артикулы, количества и комментарий ${h(o.id)}.</p><a href="https://b2b.4tochki.ru/" target="_blank" rel="noopener">Открыть кабинет поставщика ↗</a><form id="reconcile-form" data-id="${o.id}"><label class="field"><span>ID найденного заказа</span><input name="providerId" type="number" min="1" required></label><label class="check-row"><input type="checkbox" required><span>Я сверил состав и подтверждаю соответствие заказов</span></label><button class="btn">Связать с найденным заказом</button></form></div>`:''}</div>`);}
async function refreshProducts(){const r=await api('products?'+new URLSearchParams({q,page}));items=r.items;total=r.total;renderProducts();}
async function changeTab(t){tab=t;activeOrder=null;if(dialog.open)dialog.close();if(t==='overview'){status=await api('status');renderOverview();}else if(t==='products')await refreshProducts();else if(t==='order')renderNewOrder();else{orders=(await api('orders')).items;renderOrders();}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const {action,id}=b.dataset;if(busy&&['submit-order','refresh-costs'].includes(action))return;try{
if(action==='tab')await changeTab(b.dataset.tab);
if(action==='logout'){await api('logout','POST');csrf='';cart=[];items=[];orders=[];login();}
if(action==='reload')await changeTab('overview');
if(action==='prev-products'){page--;await refreshProducts();}
if(action==='next-products'){page++;await refreshProducts();}
if(action==='refresh-costs'){busy=true;b.disabled=true;b.textContent='Запрашиваем закупку…';const r=await api('purchase/refresh','POST',{ids:items.map(p=>p.id)});items=r.items;renderProducts();toast('Закупочные цены обновлены');}
if(action==='edit-price')editPrice(id);
if(action==='add-order')addOrder(id);
if(action==='close-dialog'){dialog.close();activeOrder=null;}
if(action==='remove-line'){cart.splice(Number(b.dataset.index),1);renderNewOrder();}
if(action==='submit-order'){busy=true;b.disabled=true;b.textContent='Отправляем…';const r=await api('orders/'+preview.id+'/submit','POST',{confirmation:preview.confirmation});cart=[];preview=null;dialog.close();await changeTab('orders');orderDetail(r);toast('Заказ создан у поставщика');}
if(action==='reload-orders')await changeTab('orders');
if(action==='open-order'){const o=orders.find(o=>o.id===id);if(o)orderDetail(o);}
if(action==='refresh-order'){b.disabled=true;const r=await api('orders/'+id+'/refresh','POST');orders=orders.map(o=>o.id===id?r:o);dialog.close();orderDetail(r);}
}catch(error){if(action==='submit-order'){const err=body.querySelector('#submit-error');if(err)err.textContent=error.message;b.textContent='Закрыть и проверить список заказов';b.dataset.action='reload-orders';}else toast(error.message);}finally{busy=false;b.disabled=false;}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['login-form','product-search','price-form','add-order-form','preview-order-form','reconcile-form'].includes(f.id))return;e.preventDefault();const d=Object.fromEntries(new FormData(f)),submit=f.querySelector('button[type="submit"],button:not([type])');if(submit?.disabled)return;if(submit)submit.disabled=true;try{
if(f.id==='login-form'){const r=await api('login','POST',{login:d.login,password:d.password});csrf=r.csrf;f.reset();await changeTab('overview');}
if(f.id==='product-search'){q=d.q;page=1;await refreshProducts();}
if(f.id==='price-form'){await api('prices/'+f.dataset.id,'PUT',{mode:d.mode,price:Number(d.price||0),percent:Number(d.percent||0),minimum:Number(d.minimum||0)});dialog.close();await refreshProducts();toast('Правило цены сохранено');}
if(f.id==='add-order-form'){const p=items.find(p=>p.id===f.dataset.id),warehouseId=Number(d.warehouseId),quantity=Number(d.quantity),o=p.offers.find(o=>o.warehouseId===warehouseId);const old=cart.find(l=>l.productId===p.id&&l.warehouseId===warehouseId);if(old)old.quantity+=quantity;else cart.push({productId:p.id,sku:p.sku,name:p.brand+' '+p.model,warehouseId,warehouse:o.warehouse,quantity});dialog.close();toast('Товар добавлен. Откройте «Новый заказ».');}
if(f.id==='preview-order-form'){preview=await api('orders/preview','POST',{lines:cart.map(({productId,warehouseId,quantity})=>({productId,warehouseId,quantity})),test:d.test==='on',clientName:d.clientName,clientPhone:d.clientPhone,customerId:d.customerId?Number(d.customerId):null});previewOrder();}
if(f.id==='reconcile-form'){const r=await api('orders/'+f.dataset.id+'/reconcile','POST',{providerId:Number(d.providerId)});dialog.close();orderDetail(r);}
}catch(error){if(f.id==='login-form')login(error.message);else{const n=f.querySelector('.manager-error');if(n)n.textContent=error.message;else toast(error.message);}}finally{if(submit)submit.disabled=false;}});
dialog.addEventListener('close',()=>{if(!dialog.open)activeOrder=null;});
setInterval(async()=>{if(!activeOrder||!dialog.open||document.hidden||!document.querySelector('#auto-status')?.checked||busy)return;const id=activeOrder;try{const r=await api('orders/'+id+'/refresh','POST');if(activeOrder===id&&dialog.open){dialog.close();orderDetail(r);}}catch(error){toast(error.message);}},60000);
try{const r=await api('session');csrf=r.csrf;await changeTab('overview');}catch(error){login(error.message.includes('Web Service')?error.message:'');}
