import {setupProcurement,showProcurement,clearProcurement} from './procurement.js';
import {setupManagement,showManagement,clearManagement} from './management.js';
import {sections,fieldsFor,advancedKeys,typeLabels} from '../search-model.js';
import {busyStart,wheelSpinner} from '../loading.js';
import {calculatePrice} from './pricing.js';
import {createSelection,selectionText,copyText} from '../share.js';
import {escapeHTML as h,money,formatSize} from '../domain.js';
const root=document.querySelector('#manager-app'),dialog=document.querySelector('#manager-dialog'),body=document.querySelector('#manager-dialog-content');
let csrf='',tab='overview',status={},items=[],orders=[],q='',page=1,total=0,cart=[],preview=null,activeOrder=null,busy=false,toastTimer;
const states={draft:'Предпросмотр',submitting:'Отправка · требуется сверка',submitted:'Создан у поставщика',changed:'Цена или остаток изменились',rejected:'Отклонён',unknown:'Результат требует сверки',check_failed:'Не удалось проверить остатки'};
const messages={invalid_login:'Проверьте логин и пароль.',manager_password_not_configured:'Пароль кабинета ещё не настроен на сервере.',supplier_not_configured:'Добавьте доступ к API в настройках сервера.',supplier_unavailable:'Поставщик временно не отвечает. Повторите чтение позже.',supplier_schema_unavailable:'Не удалось загрузить схему API. Проверьте соединение сервера с поставщиком.',supplier_schema_changed:'Формат API изменился. Отправка остановлена до проверки.',supplier_rejected:'Поставщик отклонил запрос.',purchase_price_unavailable:'Для этой позиции пока нет подтверждённой закупочной цены.',insufficient_supplier_stock:'На выбранном складе недостаточно товара.',purchase_changed_review_again:'Цена закупки или остаток изменились. Сформируйте новый предпросмотр.',preview_expired:'Предпросмотр устарел. Проверьте заказ ещё раз.',order_result_unknown:'Ответ о создании заказа не получен. Не отправляйте заказ повторно: сначала проверьте его в кабинете поставщика.',procurement_company_not_configured:'Доступ и ID покупателя этой компании ещё не настроены.',procurement_customer_not_available:'Покупатель не найден среди доступных этому аккаунту.',procurement_customer_identity_mismatch:'Покупатель API не совпал с выбранной компанией.',procurement_submit_not_available:'Сначала требуется проверить договор и условия получения.',supplier_orders_disabled:'Отправка заказов ещё не включена в настройках сервера.',order_already_processed:'Этот заказ уже обработан. Повторная отправка заблокирована.',origin_rejected:'Адрес сайта не совпадает с PUBLIC_ORIGIN на сервере.',csrf_rejected:'Сессия устарела. Войдите снова.',too_many_requests:'Слишком много запросов. Подождите немного.',invalid_request:'Проверьте заполнение полей.'};
const date=t=>t?new Date(typeof t==='number'?t*1000:t).toLocaleString('ru-RU'):'—';
function toast(s){const n=document.querySelector('#manager-toast');n.textContent=s;n.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('visible'),6000);}
async function api(path,method='GET',payload){const done=busyStart(),sessionAtStart=csrf;try{const r=await fetch('/api/manager/'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{})},...(payload?{body:JSON.stringify(payload)}:{}),signal:AbortSignal.timeout(90000)});let data;try{data=await r.json();}catch{throw new Error('Для кабинета нужен Web Service. Откройте адрес серверной версии каталога.');}if(path!=='login'&&sessionAtStart&&sessionAtStart!==csrf)throw new Error('Сессия завершена.');if(!r.ok){if(r.status===401&&path!=='login'){clearSession();login();}throw new Error((messages[data.detail]||'Не удалось выполнить действие.')+(data.providerCode?' Код поставщика: '+data.providerCode:''));}return data;}finally{done();}}
function login(error=''){root.innerHTML=`<main class="login-layout"><section class="login-brand"><a href="../"><span class="catalog-wordmark">Шины и диски</span></a><span class="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</span><h1>Ваш каталог.<br>Ваши решения.</h1><p>Цены, закупка и заказы —<br>в одном кабинете.</p><a class="login-back" href="../">← Вернуться в каталог</a></section><section class="login-panel"><form id="login-form"><span class="eyebrow">ДЛЯ СОТРУДНИКОВ</span><h2>Вход в кабинет</h2><p>Используйте свой доступ к кабинету менеджера.</p><label class="field"><span>Логин</span><input name="login" autocomplete="username" required value="manager"></label><label class="field"><span>Пароль</span><input name="password" type="password" autocomplete="current-password" required></label><p class="manager-error" role="alert">${h(error)}</p><button class="btn btn-primary full">Войти</button><small>Доступ к закупочным ценам и заказам защищён.</small></form></section></main>`;}
function shell(content){root.innerHTML=`<div class="manager-shell"><aside class="manager-rail"><a href="../" class="manager-logo">Шины и диски<span>КАБИНЕТ МЕНЕДЖЕРА</span></a><nav>${[['overview','01','Обзор'],['products','02','Цены и закупка'],['order','03','Новый заказ'],['orders','04','Закупки у поставщика'],['customers','05','Заказы покупателей'],['pricing','06','Автоматические цены'],['settings','07','Условия магазина'],['procurement','08','Компании и договоры']].map(([id,n,title])=>`<button data-action="tab" data-tab="${id}" class="${tab===id?'active':''}"><span>${n}</span>${title}</button>`).join('')}</nav><div class="rail-bottom"><a href="../" target="_blank" rel="noopener">Открыть витрину ↗</a><button data-action="logout">Выйти из кабинета</button></div></aside><main class="manager-workspace"><header class="manager-top"><span>Рабочее пространство</span><span>Шины и диски <i></i></span></header>${content}</main></div>`;}
const title=(small,large)=>`<div class="manager-title"><span class="eyebrow">${small}</span><h1>${large}</h1></div>`;
function renderOverview(){shell(title('ВСЁ ПОД КОНТРОЛЕМ','Обзор каталога')+`<div class="manager-metrics"><article><span>Товары в каталоге</span><strong>${status.products||0}</strong><small>Публичная витрина</small></article><article><span>Индивидуальные цены</span><strong>${status.rules||0}</strong><small>Сохранённые правила</small></article><article><span>Заказы</span><strong>${status.orders||0}</strong><small>Предпросмотры и отправленные</small></article></div><div class="manager-panels"><section class="manager-panel"><span class="eyebrow">ДАННЫЕ И ПОДКЛЮЧЕНИЕ</span><h2>Состояние системы</h2><dl><dt>Последняя выгрузка каталога</dt><dd>${h(date(status.updatedAt))}</dd><dt>API «4точки»</dt><dd>${status.supplierConfigured?'Доступ настроен':'Требуется настройка доступа'}</dd><dt>Обновление закупки</dt><dd>${h(status.purchaseSync?.status||'ожидание')} · ${status.purchaseSync?.done||0} / ${status.purchaseSync?.total||0}</dd><dt>Заявки покупателей</dt><dd>${status.customerOrders||0}</dd><dt>Отправка заказов</dt><dd>${status.ordersEnabled?'Включена':'Выключена в настройках сервера'}</dd></dl><p class="manager-note">Закупка загружается автоматически для всего каталога и при открытии товаров. Перед отправкой заказа наличие и цена проверяются повторно.</p><button class="btn btn-ghost" data-action="reload">Обновить состояние</button></section><section class="manager-panel dark"><span class="eyebrow">ЦЕНООБРАЗОВАНИЕ</span><h2>Контролируйте<br>цену и прибыль.</h2><p>Установите свою цену или наценку к закупке. Изменения сохраняются на сервере и применяются в серверной витрине.</p><button class="btn btn-lime" data-action="tab" data-tab="products">Перейти к товарам →</button></section></div>`);}
const kindNames={tires:'Шины',wheels:'Диски',tubes:'Камеры',sensors:'Датчики давления',consumables:'Расходники',oils:'Масла'};
const seasonNames={summer:'Лето',winter:'Зима',allseason:'Всесезонные',unknown:'Не указан'};
let meta={warehouses:[],facets:{}},filters={kind:'',brand:'',season:'',width:'',profile:'',diameter:'',pcd:'',wheelWidth:'',et:'',dia:'',category_filter:'',min_stock:1,...Object.fromEntries(advancedKeys.map(k=>[k,'']))},warehouseChoice=null,warehouseOpen=false,searchSerial=0;
const edits=new Map(),selection=new Map(),expandedProducts=new Set();
const key=(id,wid)=>id+':'+wid;
const photo=p=>p.image?.startsWith('assets/')?'/'+p.image:p.image;
function clearSession(){clearProcurement();clearManagement();csrf='';cart=[];items=[];orders=[];preview=null;activeOrder=null;tab='overview';searchSerial++;selection.clear();edits.clear();if(dialog.open)dialog.close();body.replaceChildren();}
function warehouseBadge(o){const w=o.warehouseInfo||{},color=/^#[0-9a-f]{6}$/i.test(w.color)?w.color:'#78909c';return `<span class="warehouse-pill" style="--warehouse-color:${color}" title="${h(o.warehouse)}">${h(w.shortName||o.warehouse)}</span><small>${h(o.warehouse)}${w.logisticDays!=null?' · '+w.logisticDays+' дн.':''}</small>`;}
function editFor(p,o){const k=key(p.id,o.warehouseId);if(!edits.has(k))edits.set(k,{price:o.salePrice,percent:o.markupPercent,profit:o.profit,mode:o.priceRule?.mode||'supplier',dirty:false});return edits.get(k);}
function productRow(p){const shown=expandedProducts.has(p.id)?p.offers:p.offers.slice(0,2);return shown.map((o,i)=>{const e=editFor(p,o),k=key(p.id,o.warehouseId),chosen=selection.get(k),qty=chosen?.quantity||0,calc=calculatePrice(o.purchasePrice,'price',e.price,qty),cost=o.purchasePrice;
const input=(field,value,min,max)=>`<input type="number" data-price-field="${field}" aria-label="${h(p.sku+' '+o.warehouse+' '+({price:'Цена продажи',percent:'Наценка в процентах',profit:'Доход в рублях'}[field]))}" step="0.01" min="${min}" max="${max}" value="${value??''}" ${!cost||o.purchaseStale?'disabled':''}>`;
return `<tr data-offer-row data-id="${h(p.id)}" data-wid="${o.warehouseId}" class="${i===0?'product-start':''} ${e.dirty?'price-dirty':''}">${i===0?`<td rowspan="${shown.length}" class="product-identity"><button class="thumb-button" data-action="product-detail" data-id="${h(p.id)}"><img src="${h(photo(p))}" alt="${h(p.brand+' '+p.model)}" loading="lazy" width="70" height="70"></button><span class="table-brand">${h(p.brand)}</span><button class="product-name" data-action="product-detail" data-id="${h(p.id)}">${h(p.model)}</button><small>${h(formatSize(p))}</small><small>Арт. ${h(p.sku)}</small><button class="table-action" data-action="edit-price" data-id="${h(p.id)}">Правило на все склады</button>${p.offers.length>2?`<button class="expand-warehouses" data-action="expand-warehouses" data-id="${h(p.id)}">${expandedProducts.has(p.id)?'Свернуть':'Ещё '+(p.offers.length-2)+' складов'}</button>`:''}</td>`:''}
<td class="warehouse-cell">${warehouseBadge(o)}</td><td><strong>${cost==null?'—':money(cost)}</strong><small class="${o.purchaseStale?'stale-price':''}">${cost==null?'Запросите цены':(o.purchaseStale?'Устарела · ':'')+h(date(o.purchaseCheckedAt))}</small></td><td>${o.supplierRetailPrice==null?'—':money(o.supplierRetailPrice)}<small>РРЦ 4точки</small></td>
<td class="price-cell">${input('price',e.price,o.minimumPrice||.01,100000000)}<button class="save-price ${e.dirty?'pending':''}" data-action="save-offer" ${e.dirty?'':'disabled'}>Сохранить</button><button class="price-reset" data-action="reset-offer">Цена 4точки</button><button class="price-reset" data-action="inherit-offer">Общее правило</button>${o.floorApplied?'<small class="floor-note">Защита дохода: +100 ₽</small>':''}</td>
<td class="price-cell">${input('percent',e.percent,0,1000)}<small data-margin>${calc?'Маржа '+calc.margin+'%':'—'}</small></td><td class="price-cell">${input('profit',e.profit,100,100000000)}<small data-profit-total>${calc?money(calc.profitTotal)+' за выбранное':'—'}</small></td>
<td><strong>${o.liveStock??o.stock}</strong><small>${o.liveStock==null?'По выгрузке':'Проверено'}</small></td><td><input class="row-quantity" data-row-quantity type="number" min="0" max="${Math.min(1000,o.liveStock??o.stock)}" step="1" value="${qty}" aria-label="Количество ${h(p.sku+' '+o.warehouse)}"><small>шт.</small></td></tr>`;}).join('');}
function filterSelect(name,label){return `<label><span>${label}</span><select name="${name}"><option value="">Все</option>${(meta.facets[name]||[]).map(v=>`<option value="${h(v)}" ${String(filters[name])===v?'selected':''}>${h(name==='kind'?kindNames[v]||v:name==='season'?seasonNames[v]||v:typeLabels[v]||v)}</option>`).join('')}</select></label>`;}
function renderProducts(){shell(title('ТОВАРЫ · СКЛАДЫ · ВАША ЦЕНА','Каталог менеджера')+`<nav class="manager-sections" aria-label="Разделы товаров">${sections.map(([kind,cat,label])=>`<button data-action="manager-section" data-kind="${kind}" data-category="${cat}" class="${filters.kind===kind&&filters.category_filter===cat?'active':''}">${h(label)}</button>`).join('')}</nav><section class="manager-panel manager-product-panel"><form id="product-search"><input type="hidden" name="kind" value="${h(filters.kind)}"><input type="hidden" name="category_filter" value="${h(filters.category_filter)}"><div class="manager-search"><input name="q" type="search" value="${h(q)}" placeholder="Артикул, модель, 205/55 R16" aria-label="Поиск товара"><button class="btn btn-primary">Найти</button><button type="button" class="btn" data-action="refresh-costs" ${items.length?'':'disabled'}>Обновить цены и остатки</button></div><div class="catalog-filter-grid">${[['brand','Бренд'],...(filters.kind==='tires'?[['season','Сезон']]:[]),...fieldsFor(filters.kind||'tires',filters.category_filter)].map(([k,l])=>filterSelect(k,l)).join('')}<label><span>Мин. количество</span><input name="min_stock" type="number" min="1" max="1000" value="${filters.min_stock}"></label></div></form>
<details class="warehouse-filter" ${warehouseOpen?'open':''}><summary>Склады · ${warehouseChoice===null?'все':warehouseChoice.size+' выбрано'}</summary><div class="warehouse-filter-actions"><button data-action="warehouses-all" class="table-action">Выбрать все</button><button data-action="warehouses-none" class="table-action">Снять все</button><button data-action="refresh-warehouses" class="table-action">Обновить склады из API</button></div><div class="warehouse-options">${meta.warehouses.map(w=>`<label style="--warehouse-color:${h(w.color)}"><input data-warehouse="${w.id}" type="checkbox" ${warehouseChoice===null||warehouseChoice.has(w.id)?'checked':''}><i></i><span>${h(w.name)}<small>${w.haveDelivery?'Доставка':w.havePickup?'Самовывоз':'Условия уточняются'}${w.logisticDays!=null?' · '+w.logisticDays+' дн.':''}</small></span></label>`).join('')}</div></details>
<p class="manager-note">Цена поставщика — ваша закупка. Розница 4точки — поле price_rozn из API. Наценка = доход / закупка; маржа = доход / продажа. Доход указан до доставки, налогов и других расходов. Минимум — закупка + 100 ₽. Если ввести меньшую цену или доход, применяется этот минимум. Изменения действуют после «Сохранить».</p>
<div class="manager-table-wrap"><table class="manager-data-table offer-table"><thead><tr><th>Товар</th><th>Склад</th><th>Цена поставщика<br>Закупка / шт.</th><th>Розничная цена<br>4точки / шт.</th><th>Моя цена, ₽</th><th>Наценка, %</th><th>Доход / шт., ₽</th><th>Остаток</th><th>Выбрать, шт.</th></tr></thead><tbody>${items.map(productRow).join('')||'<tr><td colspan="9">Нет предложений. Измените фильтры или включите склады.</td></tr>'}</tbody></table></div><div class="manager-paging"><button class="btn" data-action="prev-products" ${page===1?'disabled':''}>← Назад</button><span>Страница ${page} · товаров ${total}</span><button class="btn" data-action="next-products" ${page*20>=total?'disabled':''}>Далее →</button></div></section><aside class="selection-bar"><div id="selection-summary"></div><div><button class="btn" data-action="review-selection">Показать строки</button><button class="btn" data-action="clear-selection">Очистить</button><button class="btn" data-action="share-selection">Подборка клиенту ↗</button><button class="btn btn-primary" data-action="selection-order">Добавить в заказ</button></div></aside>`);updateSelectionSummary();}
function updateSelectionSummary(){const el=document.querySelector('#selection-summary');if(!el)return;const lines=[...selection.values()];el.innerHTML=`<strong>Выбрано ${lines.reduce((n,l)=>n+l.quantity,0)} шт.</strong><span>${money(lines.reduce((n,l)=>n+(l.price||0)*l.quantity,0))} · доход ${lines.every(l=>l.profit!=null)?money(lines.reduce((n,l)=>n+l.profit*l.quantity,0)):'требуется закупка'}</span>`;}
async function productDetail(id){const p=items.find(p=>p.id===id);if(!p)return;const fields=[['Артикул',p.sku],['Марка',p.brand],['Модель',p.model],['Размер',formatSize(p)],['Сезон',seasonNames[p.season]],['Индекс нагрузки',p.loadIndex],['Индекс скорости',p.speedIndex],['ET',p.et],['DIA',p.dia],['PCD',p.pcd],['Цвет',p.color],...(p.attributes||[]).map(a=>[a.label,a.value])];show(p.brand+' '+p.model,`<div class="manager-product-detail"><img src="${h(photo(p))}" alt="${h(p.model)}"><div><p>${h(p.description)}</p><dl>${fields.filter(([,v])=>v!=null&&v!=='').map(([k,v])=>`<dt>${h(k)}</dt><dd>${h(v)}</dd>`).join('')}</dl></div></div><h3>Склады и наличие</h3><div id="manager-extra-attributes"></div><div class="detail-offers">${p.offers.map(o=>`<div>${warehouseBadge(o)}<strong>${o.liveStock??o.stock} шт.</strong><span>${o.salePrice==null?'По запросу':money(o.salePrice)}</span></div>`).join('')}</div>`);dialog.dataset.details=id;
try{const r=await fetch('/api/products/'+encodeURIComponent(id)+'/details',{signal:AbortSignal.timeout(65000)});if(!r.ok)return;const data=await r.json();if(dialog.open&&dialog.dataset.details===id&&Array.isArray(data.attributes)){const known=new Set(fields.filter(([,v])=>v!=null&&v!=='').map(([name])=>name));const extra=data.attributes.filter(a=>!known.has(a.label));document.querySelector('#manager-extra-attributes').innerHTML=extra.length?`<h3>Дополнительные характеристики</h3><dl class="technical-grid">${extra.map(a=>`<div><dt>${h(a.label)}</dt><dd>${h(a.value)}</dd></div>`).join('')}</dl>`:'';}}catch{}
}
async function sharedSelection(){if(!selection.size){toast('Укажите количество у нужных товаров.');return;}if([...selection.keys()].some(k=>edits.get(k)?.dirty)){toast('Сначала сохраните изменённые цены выбранных товаров.');return;}const result=await createSelection([...selection.values()].map(({productId,warehouseId,quantity})=>({productId,warehouseId,quantity})));const url=new URL(result.url,location.origin).href;const text=selectionText(result,url);show('Подборка для клиента',`<p>Ссылка открывается без входа в кабинет и действует 7 дней. В подборке только цены продажи.</p><input id="shared-link" readonly value="${h(url)}" aria-label="Ссылка на подборку"><textarea id="shared-text" rows="10" readonly>${h(text)}</textarea><div class="share-actions"><button class="btn btn-primary" data-action="copy-selection">Копировать текст</button><button class="btn" data-action="copy-selection-link">Копировать ссылку</button><a class="btn" href="${h(url)}" target="_blank" rel="noopener">Открыть ↗</a></div>`);}
function show(title,html){delete dialog.dataset.details;body.innerHTML=`<div class="dialog-header"><h2>${h(title)}</h2><button class="icon-btn" data-action="close-dialog" aria-label="Закрыть">×</button></div><div class="dialog-body">${html}</div>`;if(!dialog.open)dialog.showModal();}
function editPrice(id){const p=items.find(p=>p.id===id);if(!p)return;const rule=p.priceRule;show('Цена · '+p.sku,`<h3>${h(p.brand+' '+p.model)}</h3><form id="price-form" data-id="${id}"><label class="field"><span>Правило продажи</span><select name="mode">${[['supplier','Базовая розничная цена'],['fixed','Моя фиксированная цена'],['markup','Наценка к закупочной цене']].map(([v,l])=>`<option value="${v}" ${v===rule.mode?'selected':''}>${l}</option>`).join('')}</select></label><div class="manager-form-grid"><label class="field"><span>Фиксированная цена, ₽</span><input name="price" type="number" min="0.01" max="100000000" step="0.01" value="${rule.price||''}"></label><label class="field"><span>Наценка, %</span><input name="percent" type="number" min="0" max="1000" step="0.01" value="${rule.percent||0}"></label><label class="field"><span>Минимальная наценка, ₽</span><input name="minimum" type="number" min="0" max="1000000" step="0.01" value="${rule.minimum||0}"></label></div><p class="manager-note">Индивидуальные правила складов имеют приоритет. Для сброса используйте «Цена 4точки» в строке склада. Минимальный доход — 100 ₽ за единицу. Наценка считается отдельно по закупке каждого склада и округляется вверх до 10 ₽. Закупка обновляется автоматически раз в 6 часов. Если она не обновлялась больше суток, предложение с этим правилом скрывается до обновления.</p><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Склад</th><th>Закупка</th><th>Продажа</th><th>Прибыль / шт.</th></tr></thead><tbody>${p.offers.map(o=>`<tr><td>${h(o.warehouse)}<small>${h(date(o.purchaseCheckedAt))}</small></td><td>${o.purchasePrice===null?'—':money(o.purchasePrice)}</td><td>${o.salePrice===null?'—':money(o.salePrice)}</td><td class="${o.profit!==null&&o.profit<0?'loss':''}">${o.profit===null?'—':money(o.profit)}</td></tr>`).join('')}</tbody></table></div><p id="price-error" class="manager-error" role="alert"></p><button class="btn btn-primary">Сохранить цену</button></form>`);}
function addOrder(id){const p=items.find(p=>p.id===id);if(!p)return;show('Добавить в заказ',`<h3>${h(p.brand+' '+p.model)}</h3><p class="manager-note">${h(p.sku)} · ${h(formatSize(p))}</p><form id="add-order-form" data-id="${id}"><label class="field"><span>Склад</span><select name="warehouseId">${p.offers.map(o=>`<option value="${o.warehouseId}">${h(o.warehouse)} · ${o.liveStock??o.stock} шт.${o.purchasePrice!==null?' · закупка '+money(o.purchasePrice):''}</option>`).join('')}</select></label><label class="field"><span>Количество</span><input name="quantity" type="number" min="1" max="1000" value="4" required></label><button class="btn btn-primary">Добавить</button></form>`);}
function renderNewOrder(){shell(title('ОТ ПОДБОРА К РЕЗЕРВУ','Новый заказ')+`<section class="manager-panel">${cart.length?`<div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Товар</th><th>Склад</th><th>Количество</th><th></th></tr></thead><tbody>${cart.map((l,i)=>`<tr><td><strong>${h(l.name)}</strong><small>${h(l.sku)}</small></td><td>${h(l.warehouse)}</td><td>${l.quantity}</td><td><button class="table-action" data-action="remove-line" data-index="${i}">Удалить</button></td></tr>`).join('')}</tbody></table></div><form id="preview-order-form"><div class="manager-form-grid"><label class="field"><span>Клиент (для себя)</span><input name="clientName" maxlength="150"></label><label class="field"><span>Телефон клиента (для себя)</span><input name="clientPhone" maxlength="80"></label><label class="field"><span>ID покупателя у поставщика, если нужен</span><input name="customerId" type="number" min="1"></label></div><label class="check-row"><input name="test" type="checkbox" checked><span>Тестовый заказ в статусе «я формирую»</span></label><p class="manager-note">Снимите флажок для боевого заказа с резервированием. После проверки вы ещё раз увидите сумму и подтвердите отправку. Доставка оформляется отдельно.</p><p id="order-error" class="manager-error" role="alert"></p><button class="btn btn-primary">Проверить цены и остатки →</button></form>`:`<div class="manager-empty"><h2>Начните с товаров</h2><p>Найдите артикул в разделе «Цены и закупка» и добавьте его в заказ с нужного склада.</p><button class="btn btn-primary" data-action="tab" data-tab="products">Выбрать товары →</button></div>`}</section>`);}
function previewOrder(){show('Подтверждение заказа',`<div class="order-review ${preview.test?'test-order':''}"><span class="eyebrow">${preview.test?'ТЕСТОВЫЙ ЗАКАЗ':'БОЕВОЙ ЗАКАЗ · РЕЗЕРВ ТОВАРА'}</span><h2>${money(preview.purchaseTotal)}</h2><p>Сумма закупки без доставки</p><dl><dt>Продажа клиенту</dt><dd>${money(preview.saleTotal)}</dd><dt>Разница до расходов</dt><dd>${money(preview.saleTotal-preview.purchaseTotal)}</dd></dl><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Товар / склад</th><th>Шт.</th><th>Закупка / шт.</th></tr></thead><tbody>${preview.lines.map(l=>`<tr><td>${h(l.name)}<small>${h(l.warehouse)}</small></td><td>${l.quantity}</td><td>${money(l.purchasePrice)}</td></tr>`).join('')}</tbody></table></div><p class="manager-note">Предпросмотр действителен 2 минуты. ${preview.test?'Тестовый заказ создаётся у поставщика в статусе «я формирую».':'Нажатие кнопки отправит заказ поставщику для резервирования товара.'}</p><p id="submit-error" class="manager-error" role="alert"></p><button class="btn btn-primary full" data-action="submit-order">${preview.test?'Создать тестовый заказ':'Подтвердить и отправить заказ'}</button></div>`);}
function renderOrders(){shell(title('ПРОЗРАЧНЫЙ ПРОЦЕСС','Заказы и исполнение')+`<section class="manager-panel"><div class="manager-section-top"><p>Откройте заказ, чтобы проверить статус поставщика.</p><button class="btn" data-action="reload-orders">Обновить список</button></div><div class="manager-table-wrap"><table class="manager-data-table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Закупка</th><th>Состояние</th><th></th></tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${h(o.providerNumber||o.id)}</strong><small>${h(date(o.createdAt))}${o.test?' · тестовый':''}</small></td><td>${h(o.clientName||'—')}</td><td>${money(o.purchaseTotal)}</td><td><span class="order-badge ${['unknown','submitting'].includes(o.status)?'attention':''}">${h(o.providerStatus?.statusName||states[o.status]||o.status)}</span></td><td><button class="table-action" data-action="open-order" data-id="${o.id}">Открыть →</button></td></tr>`).join('')||'<tr><td colspan="5">Заказов пока нет.</td></tr>'}</tbody></table></div></section>`);}
function orderDetail(o){activeOrder=o.id;const s=o.providerStatus||{};show('Заказ '+(o.providerNumber||o.id),`<div class="order-detail"><span class="order-badge">${h(s.statusName||states[o.status])}</span><p class="manager-note">${h(o.id)}${o.test?' · Тестовый':''}</p><h2>${money(o.purchaseTotal)}</h2><p class="manager-note">Закупка без доставки. Продажа: ${money(o.saleTotal)}</p><dl><dt>Клиент</dt><dd>${h(o.clientName||'—')} ${h(o.clientPhone||'')}</dd><dt>Оплата</dt><dd>${h(s.paymentPercent||'—')}${s.paymentPercent?'%':''}</dd><dt>Отгрузка</dt><dd>${h(s.shipmentType||'—')} ${h(s.shipmentDate||'')}</dd><dt>Пункт выдачи</dt><dd>${h(s.pickupWarehouseName||'—')} ${h(s.pickupWarehouseAddress||'')}</dd><dt>Доставка</dt><dd>${h(s.deliveryAddress||'—')}</dd><dt>Интервал доставки</dt><dd>${h(s.deliveryIntervalStart||'—')} — ${h(s.deliveryIntervalEnd||'—')}</dd><dt>Проверено</dt><dd>${h(date(o.statusCheckedAt))}</dd></dl>${o.history?.length?`<ol class="order-history">${o.history.map(e=>`<li><strong>${h(e.name)}</strong><small>${h(date(e.at))}</small></li>`).join('')}</ol>`:''}${o.providerReviewRequired?'<div class="manager-alert">Поставщик вернул номер заказа с замечанием. Проверьте состав и исполнение у поставщика перед продолжением.</div>':''}${o.providerId?`<button class="btn btn-primary" data-action="refresh-order" data-id="${o.id}">Обновить статус</button><label class="check-row"><input id="auto-status" type="checkbox" checked><span>Обновлять раз в минуту, пока открыт заказ</span></label>`:''}${['unknown','submitting'].includes(o.status)?`<div class="manager-alert"><h3>Проверьте заказ у поставщика</h3><p>Отправка могла завершиться успешно. Повторный запрос заблокирован. Сверьте артикулы, количества и комментарий ${h(o.id)}.</p><a href="https://b2b.4tochki.ru/" target="_blank" rel="noopener">Открыть кабинет поставщика ↗</a><form id="reconcile-form" data-id="${o.id}"><label class="field"><span>ID найденного заказа</span><input name="providerId" type="number" min="1" required></label><label class="check-row"><input type="checkbox" required><span>Я сверил состав и подтверждаю соответствие заказов</span></label><button class="btn">Связать с найденным заказом</button></form></div>`:''}</div>`);}
async function refreshProducts(autoPurchase=true){const serial=++searchSerial;const r=await api('products?'+new URLSearchParams({q,page,...filters,features:JSON.stringify(Object.fromEntries([...advancedKeys,'wheelWidth','et','dia'].map(k=>[k,filters[k]||'']))),warehouses:warehouseChoice===null?'':[...warehouseChoice].join(',')||'none'}));if(serial!==searchSerial||tab!=='products')return;items=r.items;total=r.total;for(const p of items)for(const o of p.offers){const k=key(p.id,o.warehouseId);if(!edits.get(k)?.dirty){edits.delete(k);const line=selection.get(k);if(line){line.price=o.salePrice;line.profit=o.profit;}}}renderProducts();if(autoPurchase&&status.supplierConfigured&&items.some(p=>p.offers.some(o=>o.purchaseStale===true))){const ids=items.map(p=>p.id);void api('purchase/refresh','POST',{ids}).then(async()=>{if(serial===searchSerial&&tab==='products'){meta=await api('catalog-filters');await refreshProducts(false);}}).catch(error=>{if(serial===searchSerial&&tab==='products')toast(error.message);});}}
async function changeTab(t){tab=t;activeOrder=null;if(dialog.open)dialog.close();if(t==='procurement'){await showProcurement();return;}if(['pricing','customers','settings'].includes(t)){await showManagement(t);return;}if(t==='overview'){status=await api('status');renderOverview();}else if(t==='products'){if(!meta.warehouses.length){meta=await api('catalog-filters');try{const saved=JSON.parse(localStorage.getItem('imkonex-manager-warehouses'));if(Array.isArray(saved))warehouseChoice=new Set(saved.filter(id=>meta.warehouses.some(w=>w.id===id)));}catch{}}await refreshProducts();}else if(t==='order')renderNewOrder();else{orders=(await api('orders')).items;renderOrders();}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const {action,id}=b.dataset;if(busy&&['submit-order','refresh-costs'].includes(action))return;try{
if(action==='tab')await changeTab(b.dataset.tab);
if(action==='logout'){await api('logout','POST');clearSession();login();}
if(action==='reload')await changeTab('overview');
if(action==='prev-products'){page--;await refreshProducts();}
if(action==='next-products'){page++;await refreshProducts();}
if(action==='refresh-costs'){busy=true;b.disabled=true;b.textContent='Запрашиваем закупку…';const r=await api('purchase/refresh','POST',{ids:items.map(p=>p.id)});for(const p of r.items)for(const o of p.offers)if(!edits.get(key(p.id,o.warehouseId))?.dirty)edits.delete(key(p.id,o.warehouseId));meta=await api('catalog-filters');await refreshProducts();toast('Цены и остатки обновлены');}
if(action==='manager-section'){filters={...Object.fromEntries(Object.keys(filters).map(k=>[k,''])),kind:b.dataset.kind,category_filter:b.dataset.category||'',min_stock:1};page=1;meta=await api('catalog-filters?'+new URLSearchParams({kind:filters.kind,category_filter:filters.category_filter}));await refreshProducts();}
if(action==='expand-warehouses'){expandedProducts.has(id)?expandedProducts.delete(id):expandedProducts.add(id);renderProducts();}
if(action==='review-selection')reviewSelection();
if(action==='remove-selection'){selection.delete(b.dataset.key);reviewSelection();updateSelectionSummary();}
if(action==='inherit-offer'){const row=b.closest('[data-offer-row]');await api('prices/'+row.dataset.id+'?warehouse='+row.dataset.wid,'DELETE');edits.delete(key(row.dataset.id,Number(row.dataset.wid)));await refreshProducts(false);}
if(action==='product-detail')productDetail(id);
if(action==='share-selection')await sharedSelection();
if(action==='copy-selection'){await copyText(document.querySelector('#shared-text').value);toast('Текст подборки скопирован');}
if(action==='copy-selection-link'){await copyText(document.querySelector('#shared-link').value);toast('Ссылка скопирована');}
if(action==='clear-selection'){selection.clear();renderProducts();}
if(action==='selection-order'){for(const line of selection.values()){const old=cart.find(l=>l.productId===line.productId&&l.warehouseId===line.warehouseId);if(old)old.quantity=line.quantity;else cart.push({...line});}await changeTab('order');}
if(action==='warehouses-all'||action==='warehouses-none'){warehouseChoice=action==='warehouses-all'?null:new Set();localStorage.setItem('imkonex-manager-warehouses',JSON.stringify(warehouseChoice===null?null:[...warehouseChoice]));page=1;warehouseOpen=true;await refreshProducts();}
if(action==='refresh-warehouses'){b.disabled=true;meta.warehouses=(await api('warehouses/refresh','POST')).warehouses;renderProducts();toast('Склады обновлены');}
if(action==='save-offer'||action==='reset-offer'){
 const row=b.closest('[data-offer-row]'),pid=row.dataset.id,wid=Number(row.dataset.wid),edit=edits.get(key(pid,wid));
 const rule=action==='reset-offer'?{mode:'supplier'}:{mode:edit.mode,price:Number(edit.price||0),percent:edit.mode==='markup'?Number(edit.percent||0):0,amount:edit.mode==='profit'?Number(edit.profit||0):0,roundTo:0.01};
 b.disabled=true;await api('prices/'+encodeURIComponent(pid)+'?warehouse='+wid,'PUT',rule);edits.delete(key(pid,wid));await refreshProducts();toast('Цена сохранена');
}
if(action==='edit-price')editPrice(id);
if(action==='add-order')addOrder(id);
if(action==='close-dialog'){dialog.close();activeOrder=null;}
if(action==='remove-line'){cart.splice(Number(b.dataset.index),1);renderNewOrder();}
if(action==='submit-order'){busy=true;b.disabled=true;b.textContent='Отправляем…';const r=await api('orders/'+preview.id+'/submit','POST',{confirmation:preview.confirmation});cart=[];preview=null;dialog.close();await changeTab('orders');orderDetail(r);toast('Заказ создан у поставщика');}
if(action==='reload-orders')await changeTab('orders');
if(action==='open-order'){const o=orders.find(o=>o.id===id);if(o)orderDetail(o);}
if(action==='refresh-order'){b.disabled=true;const r=await api('orders/'+id+'/refresh','POST');orders=orders.map(o=>o.id===id?r:o);dialog.close();orderDetail(r);}
}catch(error){if(action==='submit-order'){const err=body.querySelector('#submit-error');if(err)err.textContent=error.message;b.textContent='Закрыть и проверить список заказов';b.dataset.action='reload-orders';}else toast(error.message);}finally{busy=false;b.disabled=false;}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['login-form','product-search','price-form','add-order-form','preview-order-form','reconcile-form'].includes(f.id))return;e.preventDefault();const d=Object.fromEntries(new FormData(f)),submit=f.querySelector('button[type="submit"],button:not([type])');if(submit?.disabled)return;if(submit)submit.disabled=true;try{
if(f.id==='login-form'){const r=await api('login','POST',{login:d.login,password:d.password});csrf=r.csrf;f.reset();await changeTab('overview');}
if(f.id==='product-search'){q=d.q;for(const k of Object.keys(filters))filters[k]=d[k]|| (k==='min_stock'?1:'');page=1;await refreshProducts();}
if(f.id==='price-form'){await api('prices/'+f.dataset.id,'PUT',{mode:d.mode,price:Number(d.price||0),percent:Number(d.percent||0),minimum:Number(d.minimum||0),roundTo:10});dialog.close();await refreshProducts();toast('Правило цены сохранено');}
if(f.id==='add-order-form'){const p=items.find(p=>p.id===f.dataset.id),warehouseId=Number(d.warehouseId),quantity=Number(d.quantity),o=p.offers.find(o=>o.warehouseId===warehouseId);const old=cart.find(l=>l.productId===p.id&&l.warehouseId===warehouseId);if(old)old.quantity+=quantity;else cart.push({productId:p.id,sku:p.sku,name:p.brand+' '+p.model,warehouseId,warehouse:o.warehouse,quantity});dialog.close();toast('Товар добавлен. Откройте «Новый заказ».');}
if(f.id==='preview-order-form'){preview=await api('orders/preview','POST',{lines:cart.map(({productId,warehouseId,quantity})=>({productId,warehouseId,quantity})),test:d.test==='on',clientName:d.clientName,clientPhone:d.clientPhone,customerId:d.customerId?Number(d.customerId):null});previewOrder();}
if(f.id==='reconcile-form'){const r=await api('orders/'+f.dataset.id+'/reconcile','POST',{providerId:Number(d.providerId)});dialog.close();orderDetail(r);}
}catch(error){if(f.id==='login-form')login(error.message);else{const n=f.querySelector('.manager-error');if(n)n.textContent=error.message;else toast(error.message);}}finally{if(submit)submit.disabled=false;}});
dialog.addEventListener('close',()=>{if(!dialog.open)activeOrder=null;});
setInterval(async()=>{if(!activeOrder||!dialog.open||document.hidden||!document.querySelector('#auto-status')?.checked||busy)return;const id=activeOrder;try{const r=await api('orders/'+id+'/refresh','POST');if(activeOrder===id&&dialog.open){dialog.close();orderDetail(r);}}catch(error){toast(error.message);}},60000);
try{const r=await api('session');csrf=r.csrf;await changeTab('overview');}catch(error){login(error.message.includes('Web Service')?error.message:'');}

document.addEventListener('toggle',e=>{if(e.target.matches?.('.warehouse-filter'))warehouseOpen=e.target.open;},true);
document.addEventListener('change',async e=>{
 const input=e.target;
 if(input.dataset.warehouse){
  if(warehouseChoice===null)warehouseChoice=new Set(meta.warehouses.map(w=>w.id));
  input.checked?warehouseChoice.add(Number(input.dataset.warehouse)):warehouseChoice.delete(Number(input.dataset.warehouse));
  localStorage.setItem('imkonex-manager-warehouses',JSON.stringify([...warehouseChoice]));page=1;warehouseOpen=true;
  try{await refreshProducts();}catch(error){toast(error.message);}
 }
});
document.addEventListener('input',e=>{
 const input=e.target,row=input.closest('[data-offer-row]');if(!row)return;
 const p=items.find(p=>p.id===row.dataset.id),o=p?.offers.find(o=>o.warehouseId===Number(row.dataset.wid));if(!o)return;
 const edit=editFor(p,o),k=key(p.id,o.warehouseId),quantity=Number(row.querySelector('[data-row-quantity]').value);
 if(input.dataset.priceField){
  const field=input.dataset.priceField,value=input.value===''?NaN:Number(input.value),calc=calculatePrice(o.purchasePrice,field,value,quantity);
  if(!calc){input.setCustomValidity('Нужна положительная закупочная цена и корректная наценка.');return;}
  input.setCustomValidity('');edit.mode=field==='price'?'fixed':field==='percent'?'markup':'profit';
  if(calc){edit.price=calc.sale;edit.percent=calc.percent;edit.profit=calc.profit;}
  else{edit.price=value;edit.percent=null;edit.profit=null;}
  edit.dirty=true;row.classList.add('price-dirty');const save=row.querySelector('[data-action="save-offer"]');save.disabled=!Number.isFinite(edit.price)||edit.price<=0;save.classList.add('pending');
  for(const [name,v] of Object.entries({price:edit.price,percent:edit.percent,profit:edit.profit}))if(name!==field)row.querySelector(`[data-price-field="${name}"]`).value=v??'';
 }
 if(!Number.isInteger(quantity)||quantity<0||quantity>Math.min(1000,o.liveStock??o.stock)){row.querySelector('[data-row-quantity]').setCustomValidity('Количество превышает остаток или указано неверно.');return;}
 row.querySelector('[data-row-quantity]').setCustomValidity('');
 if(quantity){if(!selection.has(k)&&selection.size>=50){toast('В подборке может быть до 50 строк.');return;}selection.set(k,{productId:p.id,sku:p.sku,name:p.brand+' '+p.model,warehouseId:o.warehouseId,warehouse:o.warehouse,quantity,price:edit.price,profit:edit.profit});}else selection.delete(k);
 const calc=calculatePrice(o.purchasePrice,'price',edit.price,quantity);row.querySelector('[data-profit-total]').textContent=calc?money(calc.profitTotal)+' за выбранное':'—';row.querySelector('[data-margin]').textContent=calc?'Маржа '+calc.margin+'%':'—';updateSelectionSummary();
});
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'&&!e.target.dataset.fallback){e.target.dataset.fallback='1';e.target.src='/assets/product-unavailable.svg';}},true);

setupManagement({api,shell,title,show,date,toast,activeTab:()=>tab,close:()=>dialog.close(),procure:async order=>{
 for(const l of order.lines){const old=cart.find(x=>x.productId===l.productId&&x.warehouseId===l.warehouseId);if(old)old.quantity=l.quantity;else cart.push({...l});}
 await changeTab('order');const form=document.querySelector('#preview-order-form');if(form){form.elements.clientName.value=order.customer.name;form.elements.clientPhone.value=order.customer.phone;}
 toast('Позиции добавлены в закупку. Проверьте цены и остатки перед отправкой.');
}});
function reviewSelection(){show('Выбранные позиции',`<div class="manager-table-wrap"><table class="manager-data-table compact-selection"><thead><tr><th>Товар / артикул</th><th>Склад</th><th>Количество</th><th>Продажа</th><th>Доход</th><th></th></tr></thead><tbody>${[...selection.entries()].map(([k,l])=>`<tr><td><b>${h(l.name)}</b><small>${h(l.sku)}</small></td><td>${h(l.warehouse)}</td><td>${l.quantity} шт.</td><td>${money(l.price*l.quantity)}</td><td>${l.profit==null?'—':money(l.profit*l.quantity)}</td><td><button class="table-action" data-action="remove-selection" data-key="${h(k)}">Убрать</button></td></tr>`).join('')||'<tr><td colspan="6">Выберите количество рядом с нужным складом.</td></tr>'}</tbody></table></div><div class="share-actions"><button class="btn btn-primary" data-action="share-selection">Подборка клиенту ↗</button><button class="btn" data-action="selection-order">Подготовить закупку</button></div>`);}
document.addEventListener('focusout',e=>{const input=e.target,row=input.closest('[data-offer-row]');if(!input.dataset.priceField||!row)return;const edit=edits.get(key(row.dataset.id,Number(row.dataset.wid)));if(!edit)return;const field=input.dataset.priceField;input.value=edit[field]??'';});

setupProcurement({api,shell,title,activeTab:()=>tab,getLines:()=>cart,toast});
