import {startCheckout} from '../shop.js';
import {wheelSpinner} from '../loading.js';
import {escapeHTML as h,money} from '../domain.js';
import {selectionText,copyText} from '../share.js';
const root=document.querySelector('#selection');let selection;root.innerHTML=wheelSpinner('Открываем подборку');
try{const token=location.pathname.split('/').filter(Boolean).pop();const r=await fetch('/api/selections/'+encodeURIComponent(token),{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();selection=await r.json();root.innerHTML=`<div class="page-heading"><span class="eyebrow">ПОДОБРАНО ДЛЯ ВАС</span><h1>Ваш следующий<br>комплект.</h1><p>Подборка от ${new Date(selection.createdAt*1000).toLocaleDateString('ru-RU')}</p></div><div class="selection-layout"><section>${selection.lines.map(l=>`<article class="selection-item"><img src="${h(l.image.startsWith('assets/')?'/'+l.image:l.image)}" alt="${h(l.name)}" loading="lazy"><div><h2>${h(l.name)}</h2><p>${h(l.description)}</p><small>Артикул ${h(l.sku)}</small><p>${l.quantity} шт. × ${money(l.price)}</p></div><strong>${money(l.subtotal)}</strong></article>`).join('')}</section><aside class="selection-total"><span class="eyebrow">ВАШ ВЫБОР</span><h2>${money(selection.total)}</h2><p>Цена и наличие подтверждаются при оформлении. Доставка рассчитывается отдельно.</p><button id="checkout-selection" class="btn btn-primary full">Оформить заказ →</button><a class="btn btn-ghost full" href="tel:88003013688">Обсудить подбор</a><button id="copy" class="btn btn-ghost full">Копировать подборку</button><button id="print" class="btn btn-ghost full">Печать / PDF</button><p id="copy-result" role="status"></p><small>Подборка доступна до ${new Date(selection.expiresAt*1000).toLocaleDateString('ru-RU')}.</small></aside></div>`;}catch{root.innerHTML='<div class="page-heading"><h1>Подборка недоступна</h1><p>Возможно, срок действия ссылки закончился. Попросите менеджера обновить подборку.</p><a class="btn btn-primary" href="/">Открыть каталог</a></div>';}
document.querySelector('#copy')?.addEventListener('click',async()=>{try{await copyText(selectionText(selection,location.href));document.querySelector('#copy-result').textContent='Подборка скопирована';}catch(e){document.querySelector('#copy-result').textContent=e.message;}});
document.querySelector('#print')?.addEventListener('click',()=>window.print());
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'&&!e.target.dataset.fallback){e.target.dataset.fallback='1';e.target.src='/assets/product-unavailable.svg';}},true);

document.querySelector('#checkout-selection')?.addEventListener('click',()=>startCheckout(selection.lines.map(l=>({productId:l.productId,quantity:l.quantity})),()=>{}));
document.addEventListener('click',e=>{if(e.target.closest('[data-action="close-dialog"]'))document.querySelector('#dialog').close();});
