import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
const types={'.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg'};
const uri=async file=>`data:${types[path.extname(file)]};base64,${(await readFile(file)).toString('base64')}`;
const data=JSON.parse(await readFile('data/demo-catalog.json','utf8')),map={};
for(const p of data.products)if(!map[p.image])map[p.image]=await uri('frontend/'+p.image);
let html=await readFile('frontend/index.html','utf8');
html=html.replace('<link rel="stylesheet" href="./styles.css">',`<style>${await readFile('frontend/styles.css','utf8')}</style>`);
for(const file of ['assets/imkonex-cars.svg','assets/favicon.svg'])html=html.replaceAll('./'+file,await uri('frontend/'+file));
const safe=value=>JSON.stringify(value).replaceAll('<','\\u003c');
html=html.replace('<script src="./config.js"></script>',`<script>window.IMKONEX_CONFIG={mode:'demo',apiBase:'',version:'0.1.0'};window.IMKONEX_IMAGE_MAP=${safe(map)};</script>`);
html=html.replace('<script src="./data/catalog.js"></script>',`<script>window.IMKONEX_DATA=${safe(data)};</script>`);
const domain=(await readFile('frontend/domain.js','utf8')).replace(/^export /gm,'');
const app=(await readFile('frontend/app.js','utf8')).replace(/^import .*;\n/,'');
html=html.replace('<script type="module" src="./app.js"></script>',()=>`<script type="module">${domain}\nconst h=escapeHTML;\n${app}</script>`);
await mkdir('artifacts',{recursive:true});
await writeFile('artifacts/IMKONEX_WHEELS_PREVIEW.html',html);
console.log('Standalone preview generated; assets embedded, no network required.');
